### ISSUE TITLE
Implicit labels can cause reading issues on menu items elsewhere on page

### ISSUE THREAD

**Issue by LauraOH** [FreedomScientific/VFO-standards-support#10]
### Summary

> Implicit labels (wrapped around fields) without a for="ID" can cause issues reading menus and trees elsewhere on the page.  In some instances, the text of a tree item is not read at all, rendering a tree navigation inaccessible. 

### Expected result

> The text of the menuitems and treeitems should be read.

### Actual result

> The label gets read for each menu item or treeitem.  In some instances, the text of the treeitem itself doesn't get read.

#### JAWS version and build number

> Example: JAWS 18.0.4104

#### Browser and version:

> Example: IE 11.0.96

#### Example:

> Code marked up as a menu and tree but does not have the CSS and JS to operate beyond the top item
> https://codepen.io/LauraFO/full/zELENZ/

**Comment by LJWatson** [comment]
The heuristics that Jaws uses to utilise nearby text as a label when no properly associated label is available, seems to be part of the problem. Putting some content in between the ```<input type="text">``` and the menu stops Jaws behaving as described. This doesn't explain why Jaws is defaulting to its heuristics in the first place though.

**Comment by stevefaulkner** [comment]
This behaviour is also occurring in JAWS 16/IE11

**Comment by LauraOU** [comment]
Also exists under Jaws 18.0.4350 just released

**Comment by hanshillen** [comment]
Filed internally:
Bug 97136 - Implicit labels can cause reading issues on menu items elsewhere on page

**Comment by TPGJRogers** [comment]
Freedom Scientific indicates this bug to have existed only in IE 11. Closing issue.
