### ISSUE TITLE
JAWS18 doesn't read first link in the list in IE11 when navigating from textarea

### ISSUE THREAD

**Issue by Leuvarden** [FreedomScientific/VFO-standards-support#101]
### Summary

> JAWS18 doesn't read first link in the list in IE11 when navigating from textarea via Down arrow
> 
> Example:
> 1. Open http://jsbin.com/qayixesomo/1/edit in IE11
> 2. Navigate from textarea to 'Test1' link in the list using Down arrow

### Expected result

> Browser focus is set on the first link in the link, JAWS reads 'link Test1'

### Actual result

> Browser link is set on the first link, but the virtual focus is on the second link, JAWS reads 'link Test2'

### Example

> http://jsbin.com/qayixesomo/1/edit

#### JAWS version and build number

18.0.5038
 
#### Operating System and version

Windows 10 Enterprise 10.0.16299 Build 16299

#### Browser and version:

Internet Explorer 11

**Comment by jducrot** [comment]
@Leuvarden it is accurate the announcement is not happening properly with the JSBin you provided in IE11 (as well as in Chrome) even with JAWS 20. However, in this case, the issue isn't with JAWS but with the js code provided in the bin. It violates several WCAG rules so browser & AT handling is always going to be iffy at best. If you test this situation with the simple HTML structure provided in your bin (and implied by the title of this issue) you can see it works as expected in all browsers, including IE11: https://cdpn.io/TPG/debug/2637ac21fce0d7125a8b04a2621635d9
