### ISSUE TITLE
Implicit Label with SPAN is not read. 

### ISSUE THREAD

**Issue by Marimbadog** [FreedomScientific/VFO-standards-support#103]
### Summary
For the following code, the checkboxes are identified as "unlabeled checkbox". Removing the SPAN element solves the problem, or moving the input outside the label solves the problem. 

```
<label for="florida">
<input type="checkbox" id="florida" value="florida" />
<span>Florida</span></label>
```

### Expected result

I expected the name of the location to be read. 

### Actual result

All checkboxes were identified as "unlabeled checkbox". 

### Example
Run the following code:

   ```
 <ol>
      <li>
        <label for="florida">
        <input type="checkbox" id="florida" value="florida" /> 
        <span>Florida</span></label>
      </li>
      <li>
        <label for="california">
        <input type="checkbox" id="california" value="california" /> 
        <span>California</span></label>
      </li>
      <li>
        <label for="paris">
        <input type="checkbox" id="paris" value="paris" /> 
        <span>Paris</span></label>
      </li>
      <li>
        <label for="hong-kong">
        <input type="checkbox" id="hong-kong" value="hong-kong" /> 
        <span>Hong Kong</span></label>
      </li>
      <li>
        <label for="tokyo">
        <input type="checkbox" id="tokyo" value="tokyo" /> 
        <span>Tokyo</span></label>
      </li>
    </ol>
```

#### JAWS version and build number
JAWs version 2018.1807.8
 
#### Operating System and version
Windows 7

#### Browser and version:
Internet Explorer 11

**Comment by lamador** [comment]
Labels for the checkboxes are approriately read using the latest version of JAWS (ver 2020.2004.66) and IE11 (ver 11.778.18362.00) in Windows 10.
