### ISSUE TITLE
All Options in Listbox Read as "Selected"

### ISSUE THREAD

**Issue by tmatsui213** [FreedomScientific/VFO-standards-support#104]
### Summary
In this example ([https://jsfiddle.net/6kxre8nc/](https://jsfiddle.net/6kxre8nc/)), we have a simple div with a role of listbox that contains 2 divs, both which have the role of option. The options are tab-able, and when a user tabs over them, they get read as "selected" even though they don't have aria-selected="true" specified.

### Expected result
These options should not be read as selected.

### Actual result
These options get read as "selected".

### Example
[https://jsfiddle.net/6kxre8nc/](https://jsfiddle.net/6kxre8nc/)
```
<div role="listbox">
  <div role="option" tabindex="0">
    Option1
  </div>
  <div role="option" tabindex="0">
    Option1
  </div>
</div>
<input type="button" value="next" />
```

#### JAWS version and build number
2018.1807.8

 
#### Operating System and version
Windows 8.1

#### Browser and version:
Chrome (64-bit) 68.0.3440.106
Firefox (64-bit) 61.0.2

**Comment by jducrot** [comment]
@tmatsui213 as of today, using the jsfiddle you provided and JAWS 2020.2004.66, the problem does not occur anymore on Chrome (64-bit v 81.0.4044.138). It's still happening on Firefox (64-bit v 76.0.1), but the problem does not rest with JAWS here. The Aria 1.1 spec points out that [listbox widget authors should actively manage focus](https://www.w3.org/TR/wai-aria-1.1/#listbox). Furthermore, a listbox widget focus should be managed using the aria-activedescendant attribute to indicate which option is selected on load. Following these guidelines, the selected item (or lack thereof) is properly indicated on focus for the listbox widget in both browsers: https://cdpn.io/TPG/debug/JjYBMWR
