### ISSUE TITLE
JAWS reads absolutely-positioned live regions when CSS transforms are applied to the region's parent

### ISSUE THREAD

**Issue by mra11yx** [FreedomScientific/VFO-standards-support#118]
### Summary
> 
> Example:
> 1. Open JAWS
> 2. Open the following CodePen in Firefox 62: https://codepen.io/mra11yx/pen/YObLrQ
> 3. Tab to each of the buttons and activate them

### Expected result

> JAWS should not read the contents of a live region when CSS transforms are applied to / removed from an ancestor of the live region

### Actual result
> If an ARIA live region is absolutely positioned (for instance, by setting it up as a screen reader-only region so that it can be used as a "global" bucket for screen reader messages), JAWS responds to the addition or removal of the CSS transform property on any parents of this div by reading the live region's content. This does not happen if the live region is not absolutely positioned.
> While the above situation may appear to be a minor edge case, this behavior can easily occur in a production site - for example, if a transform is applied to the document body or HTML tag as a hack to make content display in a certain way. (I originally found the bug "in the wild.")

### Example

> https://codepen.io/mra11yx/pen/YObLrQ

#### JAWS version and build number
2018.1808.10

 
#### Operating System and version
Windows 7 and 10

#### Browser and version:
Firefox 62 (32-bit on Windows 7, 64-bit on Windows 10)

**Comment by JAWS-test** [comment]
* The problem persists (JAWS 2019, Firefox 68)
* It occurs not only when the CSS properties are changed at the parent element, but also at the element with the live region or a child element. And it applies to the change of several CSS properties: https://github.com/w3c/aria-practices/issues/1138#issuecomment-524163289
* The problem may be that the specification does not say exactly when a live region will be output: https://github.com/w3c/aria-practices/issues/1139

**Comment by ZoeBijl** [comment]
@JAWS-test note that the ARIA Authoring Practices is not a specification but a note. It can’t specify what a screen reader MUST do.

**Comment by JAWS-test** [comment]
@ZoeBijl That's right, I did. I didn't exactly understand that back then. The output of `alert` is clearly regulated in the ARIA specification.

**Comment by lamador** [comment]
Issue was not reproducible in Windows 10 using the latest versions of JAWS 2020 (2020.2004.66) and Firefox (76.0.1 (64-bit)).
