### ISSUE TITLE
Name Calculation for Labels is failing 

### ISSUE THREAD

**Issue by JasonAment** [FreedomScientific/VFO-standards-support#12]
### Summary

Name calculation for explicit labels is incorrect when another element is present between the input and the label. In the code sample below, the page content is included in the accessible name.  Noticed from 18.0.25XX thru 18.0.4350  
In the case below, there is an icon and a div closure tag that are causing the issue.  The heading tag is read with the label.  When I remove the icon and the enclosing div, the issue resolves.  
Also, if focus is set to an element on the page, this newly focused element becomes the Name of the inputs. This occurs with programmatic focus set with JavaScript as well as mouse selections initiated by the user.

example:
```
<h1>This heading is included in the input label</h1>
<div><input id="firstID" type="checkbox" value="on"><i aria-hidden="true"></i></div>
<label for="firstID"><span id="innerID">Lorem Ipsum</span></label>

```
### Expected result

> I expect the label to be "Lorem Ipsum"

### Actual result

> All content on the page is calculated in the name.

### Example

```
<h1>This heading is included in the input label</h1>
<div><input id="firstID" type="checkbox" value="on"><i aria-hidden="true"></i></div>
<label for="firstID"><span id="innerID">Lorem Ipsum</span></label>
```

#### JAWS version and build number

18.0.2530
 
#### Operating System and version

Windows 7-10

#### Browser and version:

IE11, 11.0.46

**Comment by stevefaulkner** [comment]
Hi @JasonAment thanks for the issue report. can you provide an actual code example from which the issue is reproducible? This can be in the form of a linked HTML page or a [codepen](https://codepen.io/pen/) or similar or a the code provided inline, for example:

```
<body>
<p>
...
</body>
```

**Comment by stevefaulkner** [comment]
here is a pen of the test case https://codepen.io/stevef/pen/XeGzdL

**Comment by stevefaulkner** [comment]
@JasonAment  I cannot reproduce the issue using the test case https://codepen.io/stevef/pen/XeGzdL with JAWS 18.0.4350 and IE11.64.16299

**Comment by poorgeek** [comment]
@stevefaulkner a recent conversation reminded me of a similar bug I found a few years ago and submitted to FreedomScientific back then. Retesting my codepen today in Jaws 2018, I can see that the problem is still there and is similar to this issue. 

https://codepen.io/poorgeek/pen/groZLz
