### ISSUE TITLE
JAWS still reading input as though it were type "password" when changed to type "text"

### ISSUE THREAD

**Issue by jeffisowens** [FreedomScientific/VFO-standards-support#121]
### Summary

> When an <input> element with type="password" is changed to type="text" (using a show password button), JAWS in IE11 is announcing "star" when new characters are input instead of announcing the letters as typed.

### Expected result

> JAWS should read out the characters as they are typed as it would in a normal text input field

### Actual result

> JAWS reads "star" for each character input

### Example

> Codepen: https://codepen.io/jeffisowens/pen/MPwqYK

#### JAWS version and build number

Version 18.0.2324
 
#### Operating System and version

Windows 7

#### Browser and version:

IE 11

**Comment by JasonAment** [comment]
This is not reproducible in recent supported versions of Windows. Updating your operating system to a supported version should resolve the issue.
Also, this is fixed in the most recent version of Jaws (2019.1903.47).
