### ISSUE TITLE
Conflict in IE11 with Insert + Alt + R

### ISSUE THREAD

**Issue by rusteinberg** [FreedomScientific/VFO-standards-support#127]
### Summary
There is a conflict using INSERT + ALT + R with Internet Explorer 11. Instead of announcing descriptive text, Internet Explorer brings up command for printing screen.

Example:
1. Using Internet Explorer 11, test a form field with aria-describedby attribute
2. Listen for announcement “Use Jaws key plus alt plus R to read descriptive text”
3. After using that keystroke, Internet Explorer brings up Print Screen command

### Expected result
JAWS announces descriptive text

### Actual result
Internet Explorer brings up Print Screen command

### Example
https://codepen.io/rusteinberg/pen/ReZgzL

For IE 11
https://s.codepen.io/rusteinberg/debug/MPvEvv/NQkzYqZYxpvA

### Additional Information
JAWS Version 2018 1805.40
IE 11.665.16229.0 copyright 2015.
Windows 10 Enterprise Version 1709, OS Build 16299.665

**Comment by JAWS-test** [comment]
In my case INS+ALT+R in IE 11 (German version) focuses the bookmark bar and does not output the text of the aria-describedby. With all browsers the problem occurs that the operating instruction (with INS+ALT+R) is output redundantly, because the output of the description takes place automatically.

**Comment by kurtjwolf** [comment]
From Freedom Scientific's "General Changes in Response to Customer Requests" for JAWS 2020, note that "You should no longer hear the message 'Press JAWS Key+ALT+R to hear descriptive text' as you navigate form controls and certain other elements on the web" (https://support.freedomscientific.com/Downloads/JAWS/JAWSWhatsNew#GeneralChanges).
