### ISSUE TITLE
Blank virtual buffer with Google docx / forms

### ISSUE THREAD

**Issue by rnickelson** [FreedomScientific/VFO-standards-support#136]
### Summary
When opening a google doc or google form in Firefox 63 with JAWS 2018 or 2019 there is a blank virtual buffer
> Brief description of the issue. Please list any specific steps.
> 
Open 
https://docs.google.com/forms/d/e/1FAIpQLSddSuMF3sntBmninfXRa4OZhAuuPjujlmPAU1rQ3Mrg0IS2mg/viewform?c=0&w=1&usp=mail_form_link
in Firefox, Notice that the virtual buffer is blank.
> Example:
> 1. Go to https://docs.google.com/forms/d/e/1FAIpQLSddSuMF3sntBmninfXRa4OZhAuuPjujlmPAU1rQ3Mrg0IS2mg/viewform?c=0&w=1&usp=mail_form_link
> 2. notice the virtual buffer is blank when navigating with arrow keys.

**Comment by willslone** [comment]
Tested using JAWS Version 2020.2004.66 and Firefox 77. The issue does not occur.
