### ISSUE TITLE
JAWS is not reading the change in value if there is vertical slider

### ISSUE THREAD

**Issue by aayushdoda** [FreedomScientific/VFO-standards-support#138]
### Summary

> JAWS is not reading the change in value if there is vertical slider. 
 
 Example:
1. Open IE
2. Go to https://www.microsoft.com/en-us/sql-server/sql-server-2017-pricing 
3. Click on 'Watch now' CTA in HERO to launch One Player video
4. Move volume slider up and down using the arrow key.
5. It reads the value only once and after that it stops reading.

### Expected result

> JAWS should read all change in the volume.

### Actual result

> JAWS is reading the change in value only once.

**Comment by jducrot** [comment]
@aayushdoda thankfully this page hasn't changed and I can confirm the problem can still be experienced using JAWS 2020.2004.66 + IE11. In this the problem appears to be with the video player markup itself not JAWS or IE11. I've run into the same issue with some video players
