### ISSUE TITLE
Can't select a radio button with Jaws and Edge with keyboard

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [FreedomScientific/VFO-standards-support#142]
### Summary

I (and some of my colleagues) can't select a radio button in a group with keyboard with Microsoft Edge and sometimes with Internet Explorer 11.
I can select the first one after focusing it with the key [Tab] and cheking it with the key [Space] but arrow keys don't let me select the other radio buttons.

Sometimes, the problem doesn't appear and then, if I re-open the page in another Edge tab, the problem appears.
I've noticed that if you test the problem by opening the web page and then opening JAWS, there may be no problem. But, if **you open JAWS and then, the web page in Edge, the problem is here**.

Most of the time, it doesn't work at all.

I've got the problem with JAWS 2018 and JAWS 2019.

I've asked help from Microsoft accessibility team here (https://support.microsoft.com/fr-fr/accessibility/disability-answer-desk) and they said that this is a JAWS problem and not an Edge problem…

### Expected result

I can choose the radio button that I want.

### Actual result

I can't choose the radio button that I want.

### Example

Code to test:
https://codepen.io/juliemoynat/pen/BGPyoz

#### JAWS version and build number
JAWS 2019.1810.64 - October 2018
JAWS 2018.1805.33

 
#### Operating System and version
Windows 10

#### Browser and version:
Microsoft Edge 44.17763.1.0
Internet Explorer 11.134.17763.0

**Comment by stevefaulkner** [comment]
Given that Edge in its current state [will not continue to be developed](https://twitter.com/stevefaulkner/status/1070761434450141185) closing this as won't fix
