### ISSUE TITLE
Do something for live regions with Zoomtext

### ISSUE THREAD

**Issue by jnurthen** [FreedomScientific/VFO-standards-support#15]
### Summary

When a live region is updated and a user is using Zoomtext something should happen. I can envision a number of ways this could be implemented. One or more of the following could be considered

1.  Play a sound so the user is aware something was updated
1. Allow a keystroke (in response to the sound) to move zoomtext focus to the live region
1. Allow a keystroke (in response to the sound) to read the live region text - even if the user does not normally have speech output enabled.

There are a number of scenarios where a magnification user would not be easily aware that something had happened outside the field of vision. This would enable a user using magnification to know that something happened (1) and then potentially discover more about what actually happened.

### Expected result

I expect live regions to be useful for screen magnification users as well as screen reader users.

### Actual result

Nothing

### Example

http://www.freedomscientific.com/Training/Surfs-Up/AriaLiveRegions.htm

### Additional Information

When the live region updates I would expect a sound and then to allow a keystroke to be pressed to move my focus to that live region.

#### JAWS version and build number

Zoomtext

 
#### Operating System and version

Windows

#### Browser and version:

All

**Comment by StommePoes** [comment]
Not just a sound. I wouldn't mind something appearing within my window view.
I always have the Reader on so #3 would also be useful-- once I grok how the whole setup works, because while it could be nice to move my focus to the live region, I think I would want to safely be able to go back to where I was (unless the proposal is my keyboard stays where it was. If so then I can tab and shift-tab to move visually back to where I was). This because I get lost easily.

**Comment by stevefaulkner** [comment]
@jnurthen Thanks James I have passed this request on to the ZoomText team and the response was positive:

> I think "Live Region" idea is great

How that translates into implementation is a more complex question as  implementation will have to be carefully thought out for the variety of ZoomText users. I will keep you updated as to progress of this.

**Comment by jnurthen** [comment]
@stevefaulkner Any updates you can provide on this?

**Comment by TPGJRogers** [comment]
Issue was forwarded to and considered by Freedom Scientific as a suggestion for improvement. Closing.
