### ISSUE TITLE
JAWS + Chrome: Multiple subsequent select elements not reading label

### ISSUE THREAD

**Issue by Swimburger** [FreedomScientific/VFO-standards-support#162]
### Summary

When tabbing through subsequent select elements in a form, the associated labels are not being read out loud in Chrome browser. This works fine in IE/EDGE.

### Expected result

The associated labels to be read out loud.

### Actual result

Only the selected value is being read out loud, but not the label.

### Example

https://output.jsbin.com/xasitut
* tab into the first select => label is read out loud as well as the value
* tab into the second select => label is **not** read out loud, but value is.

#### JAWS version and build number
2018.1802.78 ILM

#### Operating System and version
Windows 10 Enterprise (10.0.17134 Build 17134)

#### Browser and version:
Chrome 71.0.3578.98 (Official Build) (64-Bit)

**Comment by JAWS-test** [comment]
This problem no longer occurs with JAWS 2019 and Chrome 76.

**Comment by Swimburger** [comment]
Tested with JAWS 2018.1811.2 ILM and Chrome 76. The issue seems to be resolved.
