### ISSUE TITLE
JAWS reads aria-label multiple times for a table with role="img", MS Edge on Win10

### ISSUE THREAD

**Issue by skingsland** [FreedomScientific/VFO-standards-support#174]
### Summary

1. Using MS Edge browser on Windows 10, go to https://skingsland.github.io/JAWS_BUG2/index.html
2. Have JAWS read the page

### Expected result

JAWS reads "graphic table description" *once*, instead of reading the text in the table.

### Actual result

JAWS reads "graphic table description" **twice**.

### Example

Here is the HTML from the page I linked above:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
    <table role="img" aria-label="table description">
        <tr>
            <td>
                row 1
            </td>
        </tr>
        <tr>
            <td>
                row 2
            </td>
        </tr>
    </table>
</body>
</html>
```

### Additional Information

This problem doesn't happen with IE 11 on the same Windows computer; it reads "graphic table description" just *once*.

I also tried adding `aria-hidden="true"` to the `td` and `tr` elements in the table, but that didn't help.

#### JAWS version and build number
2019.1812.49 ILM Professional Edition

 
#### Operating System and version
Windows 10 Enterprise, build 17134.rs4_release.180410-1804

#### Browser and version:
Microsoft Edge 42.17134.1.0

**Comment by skingsland** [comment]
It's come to my attention that Microsoft is [planning](https://github.com/MicrosoftEdge/MSEdge) to make significant changes to the implementation of the Edge browser, basing it more heavily on the Chromium project that Google Chrome uses. Given that, I'm not sure it makes sense to fix bugs in JAWS that only exist in MS Edge and not IE.

**Comment by scottaohara** [comment]
Per the other closed issue, yes, we're going to suspend looking into Edge issues until the new version lands.  Closing for now, but we can reopen when testing with the updated browser.
