### ISSUE TITLE
JAWS announces focusable heading as editable

### ISSUE THREAD

**Issue by gdkraus** [FreedomScientific/VFO-standards-support#175]
### Summary

In Chrome and FF, if a heading is focusable and the VPC is off, when you tab to the heading, JAWS announces that it is editable. This is true for `<h1>` or `<div role="heading">
`
### Expected result

JAWS should just announce it as a heading

### Actual result

JAWS announced it as editable 

### Example

```
<h5 tabindex="0">My heading</h5>
<span tabindex="0">Something else</span>
```

### Additional Information

Wrapping the inner contents of the heading with a `<span>` solves the problem.
```
<h5 tabindex="0"><span>My heading</span></h5>
<span tabindex="0">Something else</span>

```
#### JAWS version and build number
JAWS 2019.1901.66

 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 72.0.3626.119
FF 65.0.2

**Comment by scottaohara** [comment]
@gdkraus, JAWS is likely getting tripped up by the fact that non-interactive elements have been added to the document's focus order.  What is the use case for adding `tabidnex` to non-interactive content?

**Comment by gdkraus** [comment]
This is in a Web application where the expectation is that the user will not be using the VPC. We occasionally have the need to put plain text in the tab order - we don't often, but sometimes because of the larger context of how it is displayed within the application we need to. The second element in the above code is not important whether it is natively or not natively focusable - it's just the heading that needs the tabindex in our case and where the problem occurs.

**Comment by scottaohara** [comment]
so the entire web app is wrapped in a `role="application"`?

**Comment by gdkraus** [comment]
yes

**Comment by scottaohara** [comment]
This isn't necessarily a JAWS bug then, but rather JAWS exposing the information that is sent to it via the accessibility API.

Per the following test case: https://codepen.io/anon/pen/RdVwoX

![aViewer showing the accRole of the heading's content as editable text](https://user-images.githubusercontent.com/4152514/53992048-de2c7280-40f9-11e9-82a1-9466e2716d71.png)

The accRole of the text within the heading is reported as editable text.  Unfortunately if you have to wrap the entire document in a `role=application`, it seems your work around solution might be your best bet to stop the announcement right now.
