### ISSUE TITLE
Expand not being announced in Chrome working in ie

### ISSUE THREAD

**Issue by amberderosa** [FreedomScientific/VFO-standards-support#184]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Go to https://institutional.vanguard.com/web/cf/inst-investor-home/ in Chrome
> 2. Shrink the browser in chrome to small format so you see the header become a menu button. 
3. click on the menu button to expand it. 

### Expected result

> What did you expect to happen?
Expected to hear expanded when you clicked on the menu button.
This is working correctly in Ie and JAWS. 

### Actual result

> What actually did happen?
Menu opened but did not announce. 

### Example

> Example:
> 1. Go to https://institutional.vanguard.com/web/cf/inst-investor-home/ in Chrome
> 2. Shrink the browser in chrome to small format so you see the header become a menu button. 
3. click on the menu button to expand it. 

#### JAWS version and build number

JAWS Version 18.0.1835
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome - Version 68.0.3440.75 (Official Build) (64-bit)

**Comment by JasonAment** [comment]
@amberderosa - As it turns out, this is caused by the `aria-haspopup="true"` attribute. Since the `button` is not controlling an element with `role="menu"`.  For this to work correctly, you should add `aria-controls` referencing the `id` on an element that must have the `role="menu"` attribute.

**Comment by JasonAment** [comment]
@amberderosa - the `aria-haspopup="true"` is the cause of the issue.  `aria-haspopup` has other required attributes that are missing from this control.  Since this is a navigation list and not a menu, it would be appropriate to remove `aria-haspopup` from the button.

**Comment by bknolles** [comment]
"Expanded" and "collapsed" is announced using JAWS 2020.2004.66 and Chrome 83.04.4103.61.
