### ISSUE TITLE
Use of the aria-current attribute is not correctly reflected within the Links List Dialog

### ISSUE THREAD

**Issue by accdc** [FreedomScientific/VFO-standards-support#197]
When the aria-current attribute is used on a link, it is correctly announced as being "current" when setting focus to the link in the Virtual Cursor, also when arrowing down the page as expected.

However, when Insert+F7 is used to display the Links List dialog, the link is described as being "Unavailable", which is misleading because the link is not disabled.

Within the Links List dialog, all current links should also be conveyed as being "Current" so that it matches the description as heard when using the Virtual Cursor.

This issue was confirmed on Windows7 using the latest version of JAWS 2019 in IE11, Chrome Canary, and Firefox.### Summary

Steps to reproduce:

1. Open the attached test file within IE11, Chrome, or Firefox.
2. Arrow down to the Contact link to hear it's current status.
3. Press Insert+F7 to open the Links List dialog, and arrow to the Contact link.
4. Confirm that the Contact link is described as being "Unavailable".

Expected result: The Contact link should be described as being "Current" in the Links List dialog.

Actual result: The Contact link in the Links List dialog is conveyed as being "Unavailable".

JAWS version and build number: 2019.1904.60

Operating System and version: Windows7 64bt

**Comment by accdc** [comment]
[aria-current.zip](https://github.com/FreedomScientific/VFO-standards-support/files/3218716/aria-current.zip)

**Comment by stevefaulkner** [comment]
@accdc Hi Bryan, thanks for the issue, its a known issue and a bug is filed internally 
Bug 94075 - If a link has aria-current the link is displayed as unavailable in the links list. I have added your input, hopefully this will get the bug fixed!
