### ISSUE TITLE
JAWS reads the text twice with role="alert"

### ISSUE THREAD

**Issue by ymazhar** [FreedomScientific/VFO-standards-support#198]
### Summary

`<div style="display:block !important" role="alert"><ul role="alert"><li aria-atomic="false" aria-relevant="additions removals" tabindex="0" style="clip: auto; display: block;">Hello JAWS</li></ul></div>`

### Expected result

> JAWS reads the text twice

### Actual result

> JAWS reads the text only one time

#### JAWS version and build number
JAWS 2019.1904.60
#### Operating System and version

Windows 10/64

#### Browser and version:
IE11

**Comment by JasonAment** [comment]
This is due to multiple role="alert" on the <div> and the nested <ul>.  Can you provide a codepen for this?

**Comment by ymazhar** [comment]
> This is due to multiple role="alert" on the `<div>` and the nested `<ul>`. Try removing one of them and see what result you get. Can you provide a codepen for this?
Yes, I played with this, unfortunately not helps.
https://codepen.io/yaroslav-mazhar/pen/EzBLpe

**Comment by jducrot** [comment]
@ymazhar the code in your pen is different from the code you listed in the issue description in that the modal start with display: none. This causes nothing to be announced by IE11 upon revealing the modal, not a duplicated announcement as originally stated. Newer browser can work around this pattern is some cases but there are generally 2 reliable ways to get announcements registers by screen readers regardless of the browser the code is in:
- Have the live region in the DOM on page load and populate it as needed
- Insert the live region dynamically on demand, then populate it with content

I created a quick pen document the 2 approaches and I've tested them successfully with JAWS 2020 & IE11: https://codepen.io/TPG/pen/ZEWEraX
