### ISSUE TITLE
JAWS skipps input fields when navigating through a region (role="region") with arrow key

### ISSUE THREAD

**Issue by Orthopoxvirus** [FreedomScientific/VFO-standards-support#199]
### Summary

To reproduce, visit https://codepen.io/anon/pen/LoqqEL
1. press R for region navigation
1. navigate through the first selected region with arrow-down key
1. (at the end of the first region "end of region" gets announced, if your JAWS has the appropriate setting)
1. navigate with arrow-down key through second region
   1. label for first input gets announced
   1. first input gets announced
   1. end of region gets announced

### Expected result

All inputs in a region should get focused when navigating through a region with "R" and the arrow-down/-up keys.

### Actual result

For inputs in regions, only the first input will get announced. As soon as the first input gets focused, the next keypress on arrow-down focusses the next region.

### Example

visit: https://codepen.io/anon/pen/LoqqEL

#### JAWS version and build number
JAWS Version 2019.1901.66 ILM
 
#### Operating System and version
Windows 10 pro 64bit

#### Browser and version:
tested in:
* Google Chrome Version 74.0.3729.169 (Official Build) (64-Bit)
* Firefox Quantum Version 67.0 (64-Bit)

**Comment by Orthopoxvirus** [comment]
`<input role="combobox">` work as intended when navigating by arrow-key.
Codepen updated third region.

**Comment by JAWS-test** [comment]
I can confirm the error. I can only add the following: If you navigate backwards with the up arrow, JAWS gets stuck in the input field, i.e. the contents in front of the input field or the region are no longer reached and output. The problem occurs not only with role=region, but also with other regions: https://github.com/FreedomScientific/VFO-standards-support/issues/241

**Comment by carmacleod** [comment]
Another test case with a similar "jump to the end of the form on down arrow" behavior: https://www.html5accessibility.com/html5elements/

Also, this test case shows the backward navigation (up arrow) behavior mentioned in the previous comment. What I am wondering is whether this is behaving as designed? i.e. maybe the expectation is that the user will type `NumPad +` to exit forms mode, and then use up arrow to navigate with the virtual cursor?

**Comment by stevefaulkner** [comment]
Could not reproduce issue in JAWS 2020.2004.66 ILM with Chrome Version 81.0.4044.138 (Official Build) (64-bit) or Firefox 77.0b7 (64-bit), Windows 10
