### ISSUE TITLE
JAWS only reads a limited number of characters of aria-describedby in modal dialog in IE

### ISSUE THREAD

**Issue by mberrisford** [FreedomScientific/VFO-standards-support#209]
### Summary

JAWS only reads a limited number of characters of aria-describedby in modal dialog in IE. JAWS with Chrome does not seem to have this limitation.

Example:
1. Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
2. Activate the "Add Delivery Address" button located under Modal Dialog Example.
3. Activate the "Verify Address" button to launch a second modal dialog with a lengthy aria-describedby.

### Expected result

JAWS reads the label (aria-labelledby="dialog2_label") followed by the full description (aria-describedby="dialog2_desc")

### Actual result

JAWS reads the label followed by a truncated version of the description.

### Additional Information
I have replicated this behavior in our own applications. In our case we need to limit it to 244 characters (spaces and punctuation included).

#### JAWS version and build number
JAWS 2019.1904.60
 
#### Operating System and version
Windows 10

#### Browser and version:
IE 11.437.17763.0

**Comment by menovak** [comment]
hi mberrisford,

I am looking into this issue and did reproduce a limitation of characters announced when using the dialog example you've provided a URL for, when running JAWS 2019.1904 on IE11 (aria-describedby seems to stop about the phrase "It demonstrates a scenario where..."), and when running on Chrome (aria-describedby seems to stop about the phrase "The larger a focusable..."), which is many more characters than in IE11.  

I repeated this test on FireFox using NVDA 2019.1 and aria-describedby did not have any limit, in fact it seemed to load up the entire contents multiple times, which I believe is an issue with where focus is placed when the dialog opens.

I do not have any suggestions for how to fix aria-describedby when using IE11, however, do you know aria-describedby CAN accept multiple IDs?   I realize that might not be ideal, but could you break your application aria-describedby text into multiple pieces, provide each with an ID, and string them together to produce a longer message.  I put together an example codepen using bits and pieces of the dialog and text strings:

https://codepen.io/menovak/pen/mZxxqW

Meanwhile I will ask colleagues if aria-describedby has a limit with JAWS.

Regards,
Mark
TPG Engineer

**Comment by menovak** [comment]
Update August 2019

A bug was found in the JAWS built-in script function and will be fixed in a future, perhaps the next build of JAWS 2020.  

This issue is considered closed.
