### ISSUE TITLE
[Jaws 2018 + IE 11] Dialog not read as Dialog when it opens.

### ISSUE THREAD

**Issue by ShardulGhusey** [FreedomScientific/VFO-standards-support#23]
### Summary

>The dialog is not read as dialog when opened, though it reads correctly if we click on that dialog.

### Expected result

> Jaws should read as "Dialog" when dialog opens

### Actual result

> Jaws not reading as dialog until we click on the dialog.
> Note  : The focus is on 1 of the element of dialog when it opens even then we need to click inside dialog once.

### Example

> https://gist.github.com/ShardulGhusey/0ad4efd7e8150b73d3d8608821e27ad3

### Additional Information

> Verified the behavior on Firefox. It is working fine on Firefox.

#### JAWS version and build number
Jaws 2018 17.1042 ILM 

 
#### Operating System and version

Windows 10

#### Browser and version:
IE 11

**Comment by stevefaulkner** [comment]
@ShardulGhusey a resolution to this issue is to set focus on the dialog itself when the dialog is displayed. For example, I modified the demo you provided: https://codepen.io/stevef/pen/ZajjgG

**Comment by stevefaulkner** [comment]
@ShardulGhusey Note: i could not reproduce issue using your demo in IE11 with JAWS 18.0.4530
