### ISSUE TITLE
Only few times list/Menu Items narrate correctly.

### ISSUE THREAD

**Issue by dalipkumar703** [FreedomScientific/VFO-standards-support#240]
### Summary

> Sometime listitem/menuitem narrate properly 1 OF 2, 1 of 3, ..., 1 of x otherwise narrate  1of 1, 1 of 1 in list items.
![connect-people](https://user-images.githubusercontent.com/11908216/62919923-c2707b00-bdc1-11e9-8dfa-e8a6d127d1e2.PNG)

> 
> Example:
> 1.  https://teams.webex.com/ (go to space list or contact a person or create space)

### Expected result

> What did you expect to happen?
It should narrate "contact a person 1 of 2" and "create a space 2 of 2".
### Actual result

> What actually did happen?
It  narrate "contact a person 1 of 1" and "create a space 1 of 1".
### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...
https://repl.it/@dalipkumar703/QueasyMeaslyExtraction
#### JAWS version and build number

2018.1811.30 ILM
Serial Number 600244
 
#### Operating System and version

Window 10

#### Browser and version:
Firefox 66.0.3

**Comment by JAWS-test** [comment]
The problem also occurs with JAWS 2019, but only in Firefox and not in Chrome. However, it is questionable whether this is a JAWS bug, as I don't think the source code is correct. The element with role=menubar contains child elements with aria-haspopup and aria-expanded (without role). Only in these are the elements with role=menuitem. In addition, aria-current is superfluous in this case. 
Since the output is also correct in Firefox when correctly marked (see https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html), I assume that it is not a JAWS bug. 

I tested at https://queasymeaslyextraction--dalipkumar703.repl.co/

**Comment by scottaohara** [comment]
This is not a bug originating from JAWS, as other screen readers are also having a tough time correctly parsing the markup the test case prints to the DOM:
```html
<div class="md-menu md-menu-item-container" aria-label="" role="menubar" tabindex="-1">
  <div class="md-menu-item" aria-haspopup="false" aria-expanded="false">
    <div aria-current="true" class="md-list-item" id="md-menu-item-1" role="menuitem" tabindex="0" data-md-event-key="md-menu-item-1" data-md-keyboard-key="hello" aria-label="hello" title="hello">
      hello
    </div>
  </div>
  <div class="md-menu-item" aria-haspopup="false" aria-expanded="false">
    <div aria-current="false" class="md-list-item" id="md-menu-item-3" role="menuitem" tabindex="-1" data-md-event-key="md-menu-item-3" data-md-keyboard-key="contact-a-person" aria-label="Contact a person" title="Contact a person">
      Contact a person
    </div>
  </div>
  <div class="md-menu-item" aria-haspopup="false" aria-expanded="false">
    <div aria-current="false" class="md-list-item" id="md-menu-item-5" role="menuitem" tabindex="-1" data-md-event-key="md-menu-item-5" data-md-keyboard-key="create-a-space" aria-label="Create a space" title="Create a space">
      Create a space
    </div>
  </div>
</div>
```

Revising this code to adhere to the expectations for creating a `menu` or `menubar`, and stripping out all the unnecessary ARIA and title attributes, both JAWS and NVDA will correctly announce the markup pattern.

```html
<div class="md-menu md-menu-item-container" role="menu">
  <div class="md-list-item" id="md-menu-item-1" role="menuitem" tabindex="0">
    hello
  </div>

  <div class="md-list-item" id="md-menu-item-3" role="menuitem" tabindex="-1">
    Contact a person
  </div>

  <div class="md-list-item" id="md-menu-item-5" role="menuitem" tabindex="-1">
    Create a space
  </div>
</div>
```

**Comment by dalipkumar703** [comment]
Thanks for testing and revising code @JAWS-test @scottaohara  :) .
