### ISSUE TITLE
JAWS skips main region on down arrow press

### ISSUE THREAD

**Issue by ejmarsh** [FreedomScientific/VFO-standards-support#241]
### Summary

> When in an entry field with a role of "textbox" if you press the down arrow, JAWS will skip all of the rest of the content in the main region.

### Expected result

> Virtual cursor should move to the element adjacent to the textbox.

### Actual result

> Virtual cursor skips the "main" region entirely.

### Example

> 1. Go to http://www.google.com
> 2. Using the Chrome dev tools change the role of the search bar from "combobox" to "textbox".
> 3. Place focus in the field and press the down arrow. JAWS will announce "Main region end" and the virtual cursor will try to focus on the next element after the main region. 

#### JAWS version and build number
JAWS 2019.1907.10 and up

 
#### Operating System and version
Windows 10 Enterprise. OS Build 17763.615 

#### Browser and version:
Chrome 76.0.3809.100

**Comment by JAWS-test** [comment]
I can confirm the error. However, it has already been reported: https://github.com/FreedomScientific/VFO-standards-support/issues/199

**Comment by JAWS-test** [comment]
For testing:
```
<button>button outside</button>
<main>
	text inside
	<input>
	<button>button inside</button>
	<a href=#>link inside</a>
	text inside
</main>
<a href=#>link outside</a>
text outside
```

**Comment by JAWS-test** [comment]
The problem occurs in Chrome within the following HTML elements: section, article, nav, main, footer, header, article, aside.

For some elements, such as section, footer and header, the problem is that not only the region is skipped, but the entire page content. I.e. after the input field the virtual cursor is at the end of the page.

The problem only occurs with input fields, because only with these JAWS switch to form mode when reading with the arrow keys. 

Until the problem is solved, only switching from Forms Mode Auto to SemiAuto helps (INS+6, search for Forms Mode).

In my opinion, this is a serious problem and should be addressed with high priority.

**Comment by JAWS-test** [comment]
The problem also occurs in Firefox, but not in IE 11.

**Comment by JAWS-test** [comment]
If there is a form field group (<code>fieldset, legend</code>) within the region that leads to the error, the virtual cursor does not jump to the end of the region, but to the end of the form field group.

**Comment by robmc** [comment]
> 
> ### Summary
> 
> > When in an entry field with a role of "textbox" if you press the down arrow, JAWS will skip all of the rest of the content in the main region.
> 
> ### Expected result
> 
> > Virtual cursor should move to the element adjacent to the textbox.
> 
> ### Actual result
> 
> > Virtual cursor skips the "main" region entirely.
> 
> ### Example
> 
> > 1. Go to http://www.google.com
> > 2. Using the Chrome dev tools change the role of the search bar from "combobox" to "textbox".
> > 3. Place focus in the field and press the down arrow. JAWS will announce "Main region end" and the virtual cursor will try to focus on the next element after the main region.
> 
> ### Additional Information
> #### JAWS version and build number
> 
> JAWS 2019.1907.10 and up
> #### Operating System and version
> 
> Windows 10 Enterprise. OS Build 17763.615
> #### Browser and version:
> 
> Chrome 76.0.3809.100

Replicated the issue using JAWS 2019. 

The page worked as expected using JAWS 2020.

**Comment by stevefaulkner** [comment]
@robmc this can be closed if it works fine in 2020

**Comment by JAWS-test** [comment]
Can confirm that the problem no longer occurs with current version of JAWS (2020.2004). With older versions (JAWS 2020.2003 and earlier), the problem still occurs
