### ISSUE TITLE
float affects the output of div (IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#247]
### Summary

float affects the output of div (IE 11)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>div with float</title>
		<style>
			.float
				{
				margin:10px;
				float:left;
				}
		</style>
	</head>
	<body>
		<div>without</div><div>float</div>
		<div class=float>with</div><div class=float>float</div>
	</body>
</html>
```
2. Navigate with arrow keys or Z

### Expected result
	
CSS settings like float should not affect the output.

### Actual result

div elements with float:left or float:right are output by JAWS as contiguous areas (without paragraph) when linear reading with arrow keys or during quick navigation with Z.
The problem occurs only in IE 11 and not in Chrome or Firefox. 

#### JAWS version and build number

JAWS 2019.1906.10
 
#### Operating System and version

Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19431
Chrome 76.0.3809.100
Firefox 68.0.2

**Comment by lamador** [comment]
The issue was reproducible in only in IE11 11.1016.18362.0 and JAWS 2020.2008.24 on Windows 10.
