### ISSUE TITLE
Label is not output for checkboxes and radiobuttons (IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#248]
### Summary

Label is not output for checkboxes and radiobuttons (IE 11)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>label and checkbox</title>
	</head>
	<body>
		1: <label>enclosing label <input type=checkbox></label> outside<br>
		2: <label><input type=checkbox> enclosing label</label> outside<br>
		3: <label>enclosing <input type=checkbox> label</label> outside<br>
		4: <label for=1>label for</label> <input type=checkbox id=1> outside<br>
		5: <input type=checkbox id=2> outside <label for=2>label for</label> <br>
	</body>
</html>
```
2. Navigate with Tab
3. Search the source code for "checkbox" and replace it with "radio".
4. Navigate with Tab

### Expected result

Label is output

### Actual result

* With tab navigation, the label for or enclosing label is not output. Instead, the text behind it is output.
* With enclosing labels, the problem only occurs if the label is completely in front of or behind it, i.e. not with the 3rd example.
* With label for, the problem only occurs when the label is in front of the checkbox/radiobutton, i.e. not with the 5th example.
* Problem occurs in IE 11 since JAWS 18 until JAWS 2019 and only with tab navigation.
* Problem occurs with radio buttons only when JAWS is not in Forms mode.
* The problem does not occur in Firefox and Chrome.
* Since the problem is serious, it should be resolved soon.

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19431
Chrome 76.0.3809.100
Firefox 68.0.2

**Comment by JAWS-test** [comment]
It is the same problem as described at https://github.com/FreedomScientific/VFO-standards-support/issues/115 . My problem description is more general, so the old problem could be closed and the current one solved.

**Comment by lamador** [comment]
The issue with the labels for both the checkboxes and radio buttons occurs only in IE11 11.1016.18362.0 with JAWS 2020.2008.24 on Windows 10 when navigating using the {{Tab}} key. The labels are properly announced when navigating using the virtual PC cursor.

**Comment by JAWS-test** [comment]
@lamador I do not understand why the issue is closed. It is not an IE 11 bug, but a bug in JAWS. If you check the example with Inspect.exe, you will see that the label is correctly passed to the Accessiblity API
