### ISSUE TITLE
Wrong output of hidden label 

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#251]
### Summary

Wrong output of hidden label 

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>hidden label</title>
	</head>
	<body>
		<h2>hidden, label for</h2>
		<div hidden><label for=1>outside</label></div> <input id=1><br>
		<label for=2 hidden>label</label> <input id=2><br>
		<label for=3><span hidden>inside</span></label> <input id=3><br>
		<label for=4>part <span hidden>of inside</span></label> <input id=4><br>

		<h2>aria-hidden, label for</h2>
		<div aria-hidden=true><label for=5>outside</label></div> <input id=5><br>
		<label for=6 aria-hidden=true>label</label> <input id=6><br>
		<label for=7><span aria-hidden=true>inside</span></label> <input id=7><br>
		<label for=8>part <span aria-hidden=true>of inside</span></label> <input id=8><br>

		<h2>hidden, aria-labelledby</h2>
		<div hidden><span id=a>outside</span></div> <input aria-labelledby=a><br>
		<span id=b hidden>label</span> <input aria-labelledby=b><br>
		<span id=c><span hidden>inside</span></span> <input aria-labelledby=c><br>
		<span id=d>part <span hidden>of inside</span></span> <input aria-labelledby=d><br>

		<h2>aria-hidden, aria-labelledby</h2>
		<div aria-hidden=true><span id=e>outside</span></div> <input aria-labelledby=e><br>
		<span id=f aria-hidden=true>label</span> <input aria-labelledby=f><br>
		<span id=g><span aria-hidden=true>inside</span></span> <input aria-labelledby=g><br>
		<span id=h>part <span aria-hidden=true>of inside</span></span> <input aria-labelledby=h><br>
	</body>
</html>
```
2. Navigate with Tab

### Expected result

According to the specification, hidden text should be output as label when using label for or aria-labelledby or aria-describedby. However, this only applies if the label itself or an ancestor element is hidden, i.e. example 1 and 2.
So my expectation would be:
* The output is uniform in all browsers.
* The hidden label is output in example 1 and 2 (hidden outside or at the label).
* The hidden label is not output in example 3 and 4 (hidden inside).
* It makes no difference whether hidden or aria-hidden or visibility:hidden, whether label for or aria-labelledby or aria-describedby is used.

#### Specification:

https://w3c.github.io/accname/: "If the current node is hidden and is not directly referenced by aria-labelledby or aria-describedby, nor directly referenced by a native host language text alternative element (e.g. label in HTML) or attribute, return the empty string. Hidden: Indicates that the element is not visible, perceivable, or interactive to any user. An element is considered hidden if it or any one of its ancestor elements is not rendered or is explicitly hidden."

https://www.w3.org/TR/wai-aria-1.2/: "Text equivalents for hidden referenced objects may still be used in the name and description calculation [ACCNAME-1.1] even when not included in the accessibility tree. Hidden: Indicates that the element is not visible, perceivable, or interactive to any user. An element is considered hidden if it or any one of its ancestor elements is not rendered or is 
explicitly hidden."

https://w3c.github.io/aria-practices/: "It incorporates content from elements regardless of their visibility, i.e., it even includes content from elements with the HTML hidden attribute, CSS display: none, or CSS visibility: hidden in the calculated name string."

https://w3c.github.io/using-aria/: "By design, hiding the content (using CSS display:none or visibility:hidden or the HTML hidden attribute) of the element(s) referenced by aria-labelledby and aria-describedby does not stop the content from being used to provide the name/description"

### Actual result

* The output is not uniform in the browsers.
* The hidden label in examples 1 and 2 are not always output.
* The hidden label in examples 3 and 4 are sometimes output.
* It makes a difference whether hidden or aria-hidden or visibility:hidden, whether label for or aria-labelledby or aria-describedby is used.
* visibility:hidden is only different from hidden in Chrome. 
* in all browsers display:none is output as hidden. 

The numbers indicate the examples in which the hidden label is output. In brackets the output with NVDA

#### IE
* hidden, label for: 3, 4 (1, 2, 3, 4)
* aria-hidden, label for: - (1, 2, 3, 4)
* hidden, aria-labelledby: 1, 2, 3 (1, 2, 3, 4)
* aria-hidden, aria-labelledby: 1, 2, 3 (1, 2, 3, 4)
* hidden, aria-describedby: 1, 2, 3, 4 (1, 2, 3, 4)
* aria-hidden, aria-describedby: 1, 2, 3, 4 (1, 2, 3, 4)

#### Firefox
* hidden, label for: - (-)
* aria-hidden, label for: - (-) 
* hidden, aria-labelledby: 1, 2 (1, 2)
* aria-hidden, aria-labelledby: 1, 2 (1, 2)
* hidden, aria-describedby: 1, 2 (1, 2)
* aria-hidden, aria-describedby: 1, 2 (1, 2)

#### Chrome
* hidden, label for: 1 (1)
* visibility:hidden, label for: - (-)
* aria-hidden, label for: 1, 2  (1, 2)
* hidden, aria-labelledby: 1, 2 (1, 2)
* aria-hidden, aria-labelledby: 1, 2 (1, 2) 
* hidden, aria-describedby: 1, 2 (1, 2)
* aria-hidden, aria-describedby: 1, 2 (1, 2) 

#### Screenreader

JAWS 2019.1907.42
NVDA 2019.2
 
#### Operating System and version

Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19431
Chrome 76.0.3809.100
Firefox 68.0.2

**Comment by mcking65** [comment]
I don't think the `for` attribute is supposed to provide a label if it is on an element that is hidden. So, the first two sets of examples should yield different results from the second two sets.

**Comment by JAWS-test** [comment]
According to https://w3c.github.io/accname/ hidden should be output at <code>aria-labelledby</code> and <code>label for</code> identical

**Comment by mcking65** [comment]
Nop, these are two separate conditions:

>1) If the current node is hidden and is not directly referenced by aria-labelledby or aria-describedby, 
>
>2) nor directly referenced by a native host language text alternative element (e.g. label in HTML) or attribute,

The word "hidden" in the first condition islogically associated with an "and" to aria-labelledby and aria-describedby. It is not logically associated with the second condition. For hidden to apply to the second condition, it would have to be written as follows:

>1) If the current node is hidden and is not directly referenced by aria-labelledby or aria-describedby, 
>
>2) nor hidden and directly referenced by a native host language text alternative element (e.g. label in HTML) or attribute,

However, I think the wording is awkward and thus ambiguous. So, it should probably rephrased more like:

>If the current node is hidden and is not directly referenced by aria-labelledby or aria-describedby, 
>or if it is directly referenced by a native host language text alternative element (e.g. label in HTML) or attribute,
>return the empty string.

**Comment by JAWS-test** [comment]
Thank you for explaining, I misunderstood it as non-native English speaker. Unfortunately I still don't understand the case with <code>label for</code>. What do you think the test page should look like and what results should I get on my test page?

**Comment by JAWS-test** [comment]
See: https://github.com/w3c/accname/issues/57#issuecomment-529048546

**Comment by stevefaulkner** [comment]
appears to be browser/spec bugs so closing
