### ISSUE TITLE
Output of the entire area content for buttons (IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#253]
### Summary

Output of the entire area content for buttons (IE 11)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>button</title>
	</head>
	<body>
		<div aria-hidden=false>before <button>button</button> after</div>
		<div role=undefined>before2 <button>button2</button> after2</div>
	</body>
</html>
```
2. Navigate with Tab key 

### Expected result

Correct output of button labeling

### Actual result 

* Before the output of the button label, the entire area content is output. This can be the entire page content, so that the purpose of the buttons in tab navigation is no longer perceptible.
* Only in IE 11
* Also occurs with other elements that get the focus (e.g. div with tabindex=0), but not with links.
* Occurs when the area has certain ARIA roles or attributes, such as aria-hidden=false or unknown ARIA roles.
* The ARIA attributes and roles are superfluous or wrong. Unfortunately, they are still used on many pages, so the problem occurs very often. For this reason, I plead in favour of a speedy remedy

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Internet Explorer 11.1268.16299.0

**Comment by stevefaulkner** [comment]
Closing this issue as wontfix as its IE only
