### ISSUE TITLE
Change of overflow and position leads to output of live regions (Firefox)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#262]
### Summary

Change of overflow and position leads to output of live regions (Firefox)

1. Save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>live region</title>
	</head>
	<body>
		<div aria-live=polite id=1>
			live region
		</div>
		<p>
		<button onClick="document.getElementById('1').setAttribute('style','position:absolute;');">position</button>
		<button onClick="document.getElementById('1').setAttribute('style','overflow:hidden;');">overflow</button>
		<button onClick="document.getElementById('1').removeAttribute('style');">remove style attribute</button>
		</p>
	</body>
</html>
```
2. Activate all 3 buttons one after the other

### Expected result
CSS changes should not cause output of live regions (except visibility changes with display, hidden, aria-hidden and visibility)

### Actual result
Change of overflow and position leads to output of live regions (only with Firefox)

See also https://github.com/w3c/aria-practices/issues/78 and many other problems with live regions: https://github.com/FreedomScientific/VFO-standards-support/issues?q=live+region

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by lamador** [comment]
The issue was not reproducible using the latest version of JAWS (2020.2006.12), Chrome (84.0.4147.89), Firefox (78.0.2) and IE11 (11.959.18362.0) on Windows 10.
