### ISSUE TITLE
JAWS 18 not reading out select labels in Chrome

### ISSUE THREAD

**Issue by cordeliadillon** [FreedomScientific/VFO-standards-support#27]
### Summary

In Chrome, JAWS is not reading out the associated label for a `<select>` when I have focus on the select.

Steps:
1. Go to my test page: https://codepen.io/cordelia/pen/bYPYrj
2. Tab to the select dropdown.

#### Expected result

JAWS should read something like "Test Select, combobox, Option A."

#### Actual result

JAWS reads "Option A."

### Additional Information

I'm not sure if this is specifically a JAWS bug or a Chrome bug or a mix of both. See related [Chrome bug 687621](https://bugs.chromium.org/p/chromium/issues/detail?id=687621).

Screen reader | Browser | Output
------------ | ------------- | -------------
JAWS 18.0.4350 | Firefox | Test Select, combobox, Option A, to change selection press arrow keys
JAWS 18.0.4350 | IE 11 | Test Select, combobox, Option A, 1 of 3, to change the selection use the arrow keys
JAWS 18.0.4350 | Chrome | **Option A**
NVDA 2017.3 | Chrome | Test Select, combobox, collapsed, Option A
VoiceOver | Chrome | **Option A, menu item**
VoiceOver | Safari | Option A, Test Select, popup button

#### JAWS version and build number

JAWS Version 18.0.4350

#### Operating System and version

Windows 10

#### Browser and version:

Chrome Version 62.0.3239.84

**Comment by stevefaulkner** [comment]
thanks @cordeliadillon will look into it

**Comment by stevefaulkner** [comment]
@cordeliadillon tested in JAWS 2018 and Chrome Version 63.0.3239.84 JAWS announces the `select` label correctly via `tab`, and via `C` virtual cursor key. So it seems like the issue has been fixed.

Also found this in the [release notes](http://www.freedomscientific.com/Downloads/jaws/JAWSWhatsNew#Enhancements) for the latest JAWS 2018:

> Resolved an issue where JAWS was not identifying combo boxes as expected in Chrome.
