### ISSUE TITLE
JAWS 2018 not navigating by article on the web

### ISSUE THREAD

**Issue by arodenbeck** [FreedomScientific/VFO-standards-support#28]
The behavior for navigating by region in web documents seems to have changed. Some regions place you on the first line of the region, while others focus the word which begins the container. Articles don't ever seem to gain focus, although they are read "article" ... "article end".

Steps to reproduce:
1. Visit: https://applevis.com/blog/apple-braille-ios-news/apple-releases-ios-112-bringing-many-fixes-braille-and-voiceover-users
2. Navigate down the page using just the r key.

Expected:
In JAWS 18.0.4352 one hears:
banner
Form
search region
navigation region
You are here navigation region
main region
banner
article
banner
navigation region
article
 banner
navigation region

Actual:
In JAWS 2018 Build 1710.42 one hears:
AppleVis
Log in/Register
Search this site 
navigation region
You are here navigation region
main region
Apple Releases iOS 11.2; Bringing Many Fixes for Braille and VoiceOver Users 
Submitted by AppleVis on 2 December, 2017 and last modified on 2 December, 2017
navigation region
Siri voice fixes
navigation region
Read text in Photos
navigation region

The wording at the top of the blog post "Apple Releases iOS...", which is focused one press of the letter r after the main region, is what JAWS 18 identifies as a banner. This can also be seen with one more press, which yields "Submitted by AppleVis..." In the previous version banner was called out, and focus was placed on the word banner. This is not noted because it is wrong, but to demonstrate the difference in functionality.
What is wrong, is that pressing r never results in "article", which is what would have been expected in JAWS 18.0.4352.

Operating System: Windows Version	10.0.16299 Build 16299
Browser: Firefox ESR - 52.5.0 64-bit

**Comment by arodenbeck** [comment]
@ljwatson I agree with you that articles are not landmarks, however they are a very useful unit when navigating a page. Will this functionality be moved to a different key, as it is still a desired behavior regardless of the element's role.

**Comment by stevefaulkner** [comment]
@arodenbeck have discussed internally, will file a feature enhancement to provide navigation via article, separate from region, would that be useful to you?

**Comment by arodenbeck** [comment]
@stevefaulkner that sounds perfect. Thank you both for looking into this.

**Comment by stevefaulkner** [comment]
Added request to existing bug about the issue Bug 98210 - jaws 2018 not seeing same amount of Regions on web page that 18 does

**Comment by StommePoes** [comment]
I can't tell which version of JAWS I'm running, but using @LJWatson's website, I'm moving my landmark regions though she has &lt;header&gt;s inside her &lt;article&gt;s so I might be moving by banner (and since that shouldn't happen, should I file a separate bug?)

**Comment by stevefaulkner** [comment]
@StommePoes still occuring in JAWS 2018, so yes please file an issue

**Comment by stevefaulkner** [comment]
closing as is fixed in next release
