### ISSUE TITLE
Zoomtext: Focus not visible in iFrame (Chrome)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#280]
### Summary

Zoomtext: Focus not visible in iFrame (Chrome)

1. Save as HTML file:
```
<!DOCTYPE html>
<html>
<body>
	<p>example from <a href=https://www.w3schools.com/html/tryit.asp?filename=tryhtml_youtubeiframe_controls">https://www.w3schools.com/html/tryit.asp?filename=tryhtml_youtubeiframe_controls</a></p>
	<iframe width="420" height="345" src="https://www.youtube.com/embed/tgbNymZ7vqY?controls=0"></iframe>
</body>
</html>	
```
2. Tab through the elements of the video player

### Expected result
Focus of Zoomtext visible on all elements

### Actual result
* IE 11, Firefox: ok
* Chrome: 
	* Focus not visible on elements within the iFrame 
	* Focus of zoom text remains on the frame of the video or on the first element within the video
	* Problem does not occur with videos without iFrame (e.g. on the Youtube page)
	* Problem also occurs with other videos in iFrames (e.g. Vimeo)

#### JAWS version and build number

Zoomtext 2018
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.8.0
IE 11.1268.16299.0

**Comment by JAWS-test** [comment]
For the same reason, JAWS 2019 does not seem to be able to output the Tab controls. This error also only occurs with Chrome and not with IE 11 and Firefox - and it only occurs if the Youtube or Vimeos videos are in an iFrame.

**Comment by bknolles** [comment]
Reproduced issue using the provided test code in Chrome 76.0.3809.132 using ZoomText 2018, 2019, and 2020. 

Using the latest version of Chrome (81.0.4044.138), the issue no longer exists.

The latest builds of ZoomText 2018, 2019, and 2020 perform as expected when tabbing through the elements of the video player; Focus enhancements and Speech work as expected, highlighting and speaking the elements as you tab through the video player.
