### ISSUE TITLE
JAWS license agreement color issues in high-contrast mode

### ISSUE THREAD

**Issue by fstorr** [FreedomScientific/VFO-standards-support#29]
### Summary

Note: I realise this isn't a web-standards issue, but this is the most accessible place to file a JAWS bug.

In Windows high-contrast mode, the license agreement text is bright yellow on a white background, which makes it incredibly hard to read.
 
Example:
1. Turn on Windows high-contrast mode.
2. Install JAWS / an update to JAWS.
3. After your PC has re-started, you'll be presented with the license agreement window, which contains the license agreement text.

### Expected result
Text should be readable and should have a contrast of at least 4.5:1.

### Actual result
Text is almost illegible.

### Example
![JAWS license agreement panel in Windows high-contrast mode. The text is bright yellow and the background is white.](https://user-images.githubusercontent.com/169471/34028793-faef42a8-e119-11e7-822f-0cb303709cfc.PNG)

#### JAWS version and build number
JAWS 2018 (build 1712.10 ILM)
 
#### Operating System and version
Windows 10 Enterprise

**Comment by stevefaulkner** [comment]
@fstorr well its kiand of related as I think that is a web view, anyway it something that needs to be investigated, will look into it, thanks!

**Comment by stevefaulkner** [comment]
filed internally - Bug 98254 - JAWS license agreement color issues in high-contrast mode

**Comment by ggordon-vfo** [comment]
Fixed in JAWS 2018 in the February 2018 update. Fix applies to JAWS 2019 as well.
