### ISSUE TITLE
JAWS announces alert twice when content is injected and then removed from the page

### ISSUE THREAD

**Issue by graemecoleman** [FreedomScientific/VFO-standards-support#30]
### Summary

I have a sample form which includes an error message which is briefly displayed if the user tabs past a certain form field without typing anything into the field. The issue appears to only affect JAWS and IE (details of which I will provide shortly) - the below demo works as expected in other environments (such as JAWS + FF and JAWS + Google Chrome).

To replicate this issue:
1. Go to https://codepen.io/graemecoleman/pen/xpwGag
2. Tab to the "Please enter some text:" form control.
3. Press Tab without entering anything into the field.
4. Visually, the text "You need to enter some text" will be immediately displayed above the field. This text is wrapped inside a container. The alert role is injected when the text is injected.

### Expected result

JAWS announces the error text once.

### Actual result

JAWS announces the error text twice - once when the error is injected into the page, and once again when it is removed.

### Example

https://codepen.io/graemecoleman/pen/xpwGag

#### JAWS version and build number

- JAWS 18.0.4532
- JAWS 2018 build 1710.42 ILM
 
#### Operating System and version

- Windows 10 Home
- 64-bit operating system 

#### Browser and version:

Internet Explorer 11.125.16299.0

**Comment by graemecoleman** [comment]
An addendum: A colleague (@menovak) found a way around this by placing the role of alert on the <div> at page load, and then changing the CSS display property from none and back to block when the message is displayed on the page. While this fixes the issue, I'm not quite sure why this should need to be necessary.

Demo and source here: https://codepen.io/menovak/pen/OzyVKd

**Comment by hanshillen** [comment]
Confirmed and filed internally as #98893

**Comment by TPGJRogers** [comment]
Issue is marked IE11. Closing.
