### ISSUE TITLE
Layout graphic (with role=presentation) in tab is output (IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#310]
### Summary

Layout graphic (with role=presentation) in tab is output (IE 11)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>img in tab</title>
	</head>
	<body>
		<img src="img/outside.png" role=presentation>
		<div role=tablist>
			<div role=tab tabindex=0>
				<img src="tab/inside.png" role=presentation>
				tab
			</div>	
		</div>	
	</body>
</html>
```
2. read with arrow keys
3. Use quick navigation (G)
4. Use element overview (INS+Ctrl+G)

### Expected result

No output of the img due to role=presentation

### Actual result 

* The graphic is output within role=tab.
* The problem does not occur when navigating with Tab key.
* The problem occurs only in IE 11 and not in Chrome and Firefox.
* The problem does not occur with alt="".

See also: https://github.com/FreedomScientific/VFO-standards-support/issues/256 and https://github.com/FreedomScientific/VFO-standards-support/issues/255

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.8.0
IE 11.1268.16299.0

**Comment by scottaohara** [comment]
cannot reproduce with JAWS 2020.2004.66 with IE11, Chrome 81 or Firefox 76.

That said, it should also be noted that `role=presentation` is only allowed on an `img` when it has an `alt=""`.  If this issue still exists in prior versions of JAWS/browser combos, it was already noted in the description for this issue that the announcement of the graphic does not occur when the image has been provided an `alt=""`, so this is the proper solution authors should follow.
