### ISSUE TITLE
Jaws does not treat menu buttons as buttons

### ISSUE THREAD

**Issue by Wildebrew** [FreedomScientific/VFO-standards-support#32]
### Summary

Jaws does not treat a button element (`<button>` or other elements that map to a button role or a button role created with ARIA) with the aria-haspopup attribute as a button but as a menu. 
e.g.
```<button aria-haspopup="true">Actions</button>```
(see also the menu button examples in the ARIA Authoring Practices guide).

If you try to navigate to menu buttons in the Jaws virtual cursor with the button shortcut "b" you won't find it, only if you use "c" that navigates to dropdowns and menus.
 
This is problematic because a menu button is a button until it has been activated.
This is also problematic because aria-haspopup has a lot of other token values (such as grid or dialog) that do not cause menus to open when a button with aria-haspopup is activated.

ON a page with a menu button and Jaws running:
1. Hit the "b" key to navigate to the menu button.

### Expected result

Jaws should locate the button and announce the role as "button has menu" or 'button, submenu".
(Jaws not announcing other values of aria-a-haspopup wil be filed in a separate issue).

### Actual result

Jaws does not find the button (it does not recognize it as a button, but as a menu).

### Example

[The APG 1.1 navigation menu](http://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html)

#### JAWS version and build number

All versions of Jaws and browsers.

 
#### Operating System and version

All versions of Windows (not verified for Windows 10).

#### Browser and version:
All browsers.

**Comment by stevefaulkner** [comment]
Thanks @Wildebrew don't expect much activity on this until new year ;-)

**Comment by Wildebrew** [comment]
No worries. I am just using some downtime at work to file issues I've
been meaning to file for a while, those are not urgent enough to
disrupt a much-needed time off for all concerned.


On 12/22/17, stevefaulkner <notifications@github.com> wrote:
> Thanks @Wildebrew don't expect much activity on this until new year ;-)
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/FreedomScientific/VFO-standards-support/issues/32#issuecomment-353627574


-- 
Work hard. Have fun. Make history.

**Comment by stevefaulkner** [comment]
@Wildebrew i think the behaviour you describe is due to the role exposed in APIs, which is role="menu button" rather than role="button". Will investigate further

**Comment by Wildebrew** [comment]
Right. but isn't the menu button role exposed by the browser different
from the menu role (i.e. the screen reader can tell the difference
between the two)?
NVDA exposes menu buttons as buttons.
The user is not in a menu until the button has been activated. Until
then it is just a button.
The only advantage of exposing a menu button as a menu is if there is
an arrow down functionality tied to it (if exposed as a button the
screen reader would intercept and override the arrow down press), but
menu buttons can be activated with enter or spacebar and should
display the same behavior as pressing the down arrow key.
I can see both sides of the argument, but I personally think exposing
this construct as a button until it's been activated is more intuitive
and semantically appropriate .. but I've never claimed to be
omnicognicent. ;)




On 1/4/18, stevefaulkner <notifications@github.com> wrote:
> @Wildebrew i think the behaviour you describe is due to the role exposed in
> APIs, which is role="menu button" rather than role="button". Will
> investigate further
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/FreedomScientific/VFO-standards-support/issues/32#issuecomment-355218049


-- 
Work hard. Have fun. Make history.

**Comment by stevefaulkner** [comment]
@Wildebrew yeah I am not disagreeing with you that it would be appropriate to include menu buttons in button navigation, I was trying to understand why they are not currently. I plan on filing a JAWS bug (enhancement) to recommend they are included.

**Comment by stevefaulkner** [comment]
filed internally as Bug 98604 - Jaws does not treat menu buttons as buttons

**Comment by ggordon-vfo** [comment]
Fixed in JAWS 2018 February 2018 update. Fix also applies to JAWS 2019.
