### ISSUE TITLE
Different output of disabled and aria-disabled at fieldset

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#322]
### Summary

Different output of `disabled` and `aria-disabled` at `fieldset`

1. Go to [disabled and aria-disabled at fieldset](https://codepen.io/jaws-test/pen/vYBMNLM)
2. Use quick navigation (X or F), overview (INS+CTRL+X, INS+F5) or read with arrow keys

### Expected result

* `disabled` and `aria-disabled` at `fieldset` should cause all interactive child elements to be disabled as well, according to the HTML and ARIA specifications.
* Consistent output between different browsers
* Consistent output between `disabled` and `aria-disabled`
* Consistent output between HTML and ARIA elements

### Actual result 

* not all form elements are disabled
* No consistent output between different browsers
* No consistent output between `disabled` and `aria-disabled`
* No consistent output between HTML and ARIA elements

#### IE 11
* `disabled` disables all elements
* `aria-disabled` disables no elements

#### Chrome, Firefox
* `disabled` disables HTML elements only
* `aria-disabled` disables all elements

#### Edge
* `disabled` disables no elements
* `aria-disabled` disables no elements

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132, 
Firefox ESR 60.9.0
IE 11.1331.16299.0
Edge 16.16299

**Comment by JAWS-test** [comment]
> The disabled attribute, when specified,causes all the form control descendants of the fieldset element, excluding those thatare descendants of the fieldset element's first legend element child, ifany, to be disabled.

https://html.spec.whatwg.org/multipage/form-elements.html#attr-fieldset-disabled

> The state of being disabled applies to the current element and all focusable descendant elements of the element on which the aria-disabled attribute is applied.

https://w3c.github.io/aria/#aria-disabled

> disabled [ button; fieldset; input; optgroup; option; select; textarea ]: aria-disabled="true"

https://w3c.github.io/html-aam/#att-disabled

**Comment by stevefaulkner** [comment]
@JAWS-test This is not a JAWS bug, there are a number of bugs in the browsers you tested in, the correct state is not exposed via the browser implemented Accessibility APIs in some cases. Suggest the appropriate course is for bugs to be filed on browsers

**Comment by JAWS-test** [comment]
And I'm also not sure if it's a bug with Firefox and Chrome, because `disabled` disables all native form fields, but not the ARIA form fields. Maybe this is so correct, only then it should be adapted in HTML AAM.

**Comment by JAWS-test** [comment]
@stevefaulkner Could you please answer my questions
