### ISSUE TITLE
ol and ul are not output differently

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#332]
### Summary

`ol` and `ul` are not output differently

1. Go to https://codepen.io/jaws-test/pen/zYYxWeY
2. Navigate with I to the list entries or read with arrow keys

### Expected result
`ol` and `ul` are output differently

### Actual result 
* `ol` and `ul` are not output differently
* The enumeration characters are output instead, even if they do not match the list type.
* The only exception is IE 11, which outputs most of the enumeration characters at `ol` and `ul` as "bullet".

See also: 
* https://github.com/w3c/html-aam/issues/256
* https://github.com/FreedomScientific/VFO-standards-support/issues/331
* https://github.com/w3c/aria/issues/961
	
#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by scottaohara** [comment]
This is not a bug as there's no mapping difference between list elements.  

If there's ever any movement on differentiating `ol` vs `ul` vs `menu` at a mapping level, then JAWS should announce them differently based on how they are exposed.
