### ISSUE TITLE
CSS influences output of tables in Chrome

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#344]
### Summary

CSS influences output of tables in Chrome

1. Go to https://codepen.io/jaws-test/pen/zYxOPjW
2. Press Ins+Ctrl+T or T or navigate with arrow keys

### Expected result

* Tables should be output as tables (independent of CSS)
* `display:table` should not lead to the output of tables

### Actual result

* Tables are not output as tables if they have certain `display` values. 
* `display:table` leads to (incorrect) output of tables (incorrect because e.g. `display:table-caption` is not recognized as table header)
* Problem does not occur in IE 11, Firefox
* Problem does not occur with Chrome with NVDA
* Cause: Chrome sends incorrect information about the operating system's Accessibility API. I still report it as a JAWS bug, because the Chrome problem has been known for many years and JAWS should therefore also analyze the source code/DOM to work around this bug.

#### JAWS version and build number

* JAWS 2019
* JAWS 2020
 
#### Operating System and version

* Windows 8
* Windows 10

#### Browser and version:

Chrome 78.0.3904.108

**Comment by ferllings** [comment]
Yes, the table is not correctly exposed.
But unfortunately we can not create a special check for a particular browser bug.
That would be difficult to maintain and that would not encourage Chrome devs. to fix it.
