### ISSUE TITLE
JS alert message is not output (Chrome)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#351]
### Summary

Go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert an press the "Try it" button

### Expected result

JAWS outputs the message

### Actual result

JAWS does not output the message

The problem does not occur with IE 11 and Firefox. Maybe it is a chrome problem, because it also occurs with NVDA.

#### JAWS version and build number

JAWS 2019.1909.28
JAWS 18
 
#### Operating System and version

Windows 2010

#### Browser and version:

Chrome  79.0.3945.79

**Comment by ferllings** [comment]
Yes it looks like a Chrome Bug: Only the dialog title is exposed "An embedded page on this page says..."

**Comment by ferllings** [comment]
Chrome bug filled : https://bugs.chromium.org/p/chromium/issues/detail?id=1084501
