### ISSUE TITLE
menubar role interferes with grid role

### ISSUE THREAD

**Issue by mamsellem** [FreedomScientific/VFO-standards-support#356]
### Summary

when grid and menubar roles are both present in the same page, selecting rows in the grid triggers "out of table" statements from JAWS.

### Expected result
(this is the behavior when grid does not have a menubar on the page)
when moving from one row to the next, we get "XXXX" row selected

### Actual result
when moving from one row to the next, we get "table", then "out of table", then row content is read.

### Example

[grid.zip](https://github.com/FreedomScientific/VFO-standards-support/files/4059877/grid.zip)
The examples are adapted from from W3C ARIA practices.
dataGridsOnly.html => expected behavior
menubarAnddataGrids.html => faulty behavior.

### Additional Information
Note that replacing role="menubar" with role="application" seems to fix the issue. 

#### JAWS version and build number

Version 18.0.2740
 
#### Operating System and version

Windows 2012 server running on a VM

#### Browser and version:

Chrome 79 for Windows

**Comment by JAWS-test** [comment]
I do not have this issue with JAWS 2019 + Chrome 79. At least not in this example (menu+grid). But I remember that I have often heard the output " Leaving table " during navigation within grids, but I never found out the cause.

When I use the Tab key to navigate from menu to grid, the output is not correct: 

```
table
Column 65535, Row 65535
Leaving menus
MainRegion 
Transactions January 1 through January 6 Grid 
Date
column 1 row 2
01-Jan-16 selected
```

False is:
* "table" (it should be "grid")
* "Column 65535, Row 65535"
* the order of the output (first "leaving menu" and "Main Region" should be output, than "grid")

**Comment by frex65** [comment]
Tested using JAWS version 2020.2004.06 and Google Chrome 81 and confirmed to be fixed.
