### ISSUE TITLE
arrow keys in JAWS 2018 do not read line by line inside table cells, even with table mode off

### ISSUE THREAD

**Issue by DavidMacDonald** [FreedomScientific/VFO-standards-support#37]
### Summary

>arrow keys in JAWS 2018 do not read line by line inside table cells, even with table mode off
> 
> Example:
> 1. Go to http://davidmacd.com/test/table-lists.html
> 2. press "T" to go to the table.
Move to cell col 2 row 2 using table keys. Press down arrow to read the list item.

### Expected result

should read the first list item inside the cell.

### Actual result

Went to the cell below.

### Example

above

### Additional Information

Arrow keys are moving cell to cell in all technologies, even with table layer off

#### JAWS version and build number

2018 build 1712 10iLM
 
#### Operating System and version
WIN 10

#### Browser and version:
Chrome, Edge... probably others... but also happens in Word tables.

**Comment by hanshillen** [comment]
Hi David,
I'm not able to reproduce the issue so far, using JAWS 2018 1712.10 ILM. I've tried your test case in IE11, Edge, Chrome 64 and Firefox ESR 52. I've also created a similar table in a Word document.
In all cases, when I navigate to cell 2,2 using table nav and press the down arrow key JAWS reads the first list item in that cell, not the cell below it.
Could you confirm if you're still seeing this issue, and if you are we should have a closer look at ahy our results are different.

**Comment by ggordon-vfo** [comment]
Does not appear to be a JAWS bug. Please reopen with additional comments if you continue to believe otherwise.
