### ISSUE TITLE
JAWS/Chrome: Down Arrow inside a Text Field inside a Section Element or Main Region causes Jump to Content near End of Page.

### ISSUE THREAD

**Issue by SuzanneKTaylor** [FreedomScientific/VFO-standards-support#370]
### Summary

If text fields or password fields are inside **Section** elements: 
- pressing down arrow inside the field jumps to the end of the page.
- pressing up arrow inside of the field has no effect and the user remains inside the  field

If text fields or password fields are inside Div elements with role of **Main**: 
- pressing down arrow inside the field jumps down the page to content outside the Main region.
- pressing up arrow inside of the field has no effect and the user remains inside the field

Example:
1. Go to http://www.manateeroad.com/test_page_forms.html
2. Enter one of the first 4 form fields on the page, however you like 
3. Once inside the form field, press the up or down arrow key

### Expected result

When you press up or down arrow, you should move to the content just above or below the form element. (This occurs with the 5th and 6th form fields on this page, which are outside of any Section elements.)

### Actual result

When you press the down arrow, you move to either: (if in a section element) whatever content is at the end of the page or (if in a main region) whatever content is after the Main region. When you press the up arrow, you do not move at all.

### Additional Information
I most recently tested on the specific configuration below, but I believe the bug is happening generally for JAWS 2020 and 2019 with recent versions of Chrome.

#### JAWS version and build number
JAWS 2019.1909.28 ILM

#### Operating System and version
Windows 10 Home
Version 1903

#### Browser and version:
Chrome 79.0.3945.130

**Comment by JAWS-test** [comment]
See #241 and #199

**Comment by SuzanneKTaylor** [comment]
Thank you. This is a very serious issue, because no workaround can really help if a user does not know that this happened. There is so much variety to this and so many possibilities, it would be impossible for a user to learn how to get around this in all situations. If a form includes various sections with other form elements and error messages, users could easily miss information and never know that they missed the information.

**Comment by JAWS-test** [comment]
I agree that it's serious. The workaround is to deactivate the automatic form mode in Jaws.

**Comment by stevefaulkner** [comment]
Could not reproduce issue in JAWS 2020.2004.66 ILM with Chrome Version 81.0.4044.138 (Official Build) (64-bit) or Firefox 77.0b7 (64-bit), Windows 10
