### ISSUE TITLE
[JAWS + IE11] aria-live not triggered when change happens on child element

### ISSUE THREAD

**Issue by ferllings** [FreedomScientific/VFO-standards-support#38]
On the first live region, the updated text is on the root of the element with aria-live.
On the second live region, the updated text is on a span child of the element with aria-live.

https://codepen.io/anon/pen/NXLLdr

#### JAWS version and build number
Tested on Jaws 17, 18.0.4534 and 2018.1712.10
 
#### Operating System and version
Windows 10

#### Browser and version:
IE 11

**Comment by IanPouncey** [comment]
Confirmed issue, as reported.

**Comment by deconspray** [comment]
As of 6/11/2018, this remains an observed issue with JAWS 2018.1805.33 ILM and IE 11.431.16299.0.

**Comment by KCollinsTO** [comment]
As of 04/18/2019, this issue is still occurring with JAWS 2019.1812.49 ILM and IE 11.1087.162990CO. Can be reproduced on the WAI-ARIA Authoring Practices 1.1 [Alert Example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/alert/alert.html) page.

**Comment by JAWS-test** [comment]
The problem persists with JAWS 2019.1907.42 and JAWS 2019.1906.10

**Comment by 1Copenut** [comment]
As of 09/02/2020 this issue is still occurring with JAWS 2020.2008.24 ILM and IE 11.1016.18362.0. Can be reproduced on the WAI-ARIA Authoring Practices 1.1 [Alert Example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/alert/alert.html) page.

**Comment by TPGJRogers** [comment]
Issue is marked IE11. Closing.
