### ISSUE TITLE
Table navigation does not work with empty cells (Chrome, Edge)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#382]
### Summary

Example:
1. Go to https://codepen.io/jaws-test/pen/KKpOopP
2. Navigation with Ctrl+Alt+Arrow keys

### Expected result

Empty cells are reached and correctly output

### Actual result

Horizontal: empty cells are not reached but skipped or further navigation is not possible
Vertical: Empty cells are not reached (a column change takes place) 

The problem occurs only in Chrome and Edge, not in Firefox.
The problem only occurs since JAWS 2020. With JAWS 2019 and earlier versions, everything works correctly.

This is a serious problem, which should be solved as soon as possible

#### JAWS version and build number
JAWS 2020.2003.13
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 80.0.3987.163
Edge 80.0.361.109

**Comment by scottaohara** [comment]
with the latest update to JAWS, 2020.2004.66, and testing on latest versions of chrome/edge, this issue does not occur.

all cells, empty or not, can be navigated to with JAWS.  when navigating to an empty cell, JAWS will announce "blank" along with the column/row as expected.

**Comment by manojirala** [comment]
Hi Scott, I still see this issue on Chrome. I have Jaws 2020.2008.24 ILM. Can you please check

**Comment by manojirala** [comment]
> with the latest update to JAWS, 2020.2004.66, and testing on latest versions of chrome/edge, this issue does not occur.
> 
> all cells, empty or not, can be navigated to with JAWS. when navigating to an empty cell, JAWS will announce "blank" along with the column/row as expected.

Hi Scott, I still see this issue on Chrome. I have Jaws 2020.2008.24 ILM. Can you please check

**Comment by JAWS-test** [comment]
@manojirala: I don't have this problem with current Chrome and JAWS (2020.2008)
