### ISSUE TITLE
JAWS with Chrome announces incorrect first-level column header in tables with two-tier headers

### ISSUE THREAD

**Issue by straydogstrut** [FreedomScientific/VFO-standards-support#384]
### Summary

In two-tier table headers spanning multiple columns, JAWS announces the last column of cells in a column as belonging to the next first-level column header.

Example: 

1. Go to https://www.w3.org/WAI/tutorials/tables/irregular/
2. Navigate to the first example with a first-level table header spanning multiple columns
3. Note that the table cells in the third column are announced as belonging to the “Venus” table header, despite being programmatically associated with the “Mars” table header.

### Expected result

The first-level column header for the current cell is correctly announced. For example: “Mars, Sold, 30,000.”

### Actual result

In the W3C Table with Irregular Headers first example, JAWS announces “Venus, Sold, 30,000” and “Venus, Sold, 5,000”, even though these cells are associated with the Mars table header.

The problem does not occur in the second example where the column header spans multiple table cells rather than multiple column headers.

The problem occurs only in Chrome, not in IE11, Edge, or Firefox.

The problem was observed in JAWS 2020.1912.11 and earlier (JAWS 2019, JAWS 2018, JAWS 18) 

The problem does not occur in JAWS 2020.2004.66

### Example

See the first W3C Tables with Irregular Headers example: https://www.w3.org/WAI/tutorials/tables/irregular/#table-with-two-tier-headers

#### JAWS version and build number

JAWS 2020.1912.11
JAWS 2019.1907.42
JAWS 2018.1811.30
JAWS 18.0.5038
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 81.0.4044.138

**Comment by stevefaulkner** [comment]
test case: https://codepen.io/stevef/pen/JjYpdEo

**Comment by frex65** [comment]
> The problem does not occur in JAWS 2020.2004.66
Teseded and confirmed fixed using Chrome 81 and JAWS 2020.2004.66.
