### ISSUE TITLE
Jaws screen reader not reading tooltip in edge browser

### ISSUE THREAD

**Issue by niaz-a-ak** [FreedomScientific/VFO-standards-support#387]
### Summary

> Jaws screen reader not reading tooltip in edge browser
> 
> Example:
> 1. Open https://dequeuniversity.com/library/aria/tooltip in edge browser
> 2. Then open Jaws screen reader and try to read the tooltip, The same is working fine in chrome browser.

### Expected result

> Jaws screen reader need to read tooltip in edge browser

### Actual result

> What actually did happen?

In edge browser Jaws didn't read tooltip.

**Comment by scottaohara** [comment]
@niaz-a-ak could you please verify if this a bug with legacy edge or latest edge based on the chromium browser engine?

**Comment by JAWS-test** [comment]
The problem does not occur with Chromium Edge with JAWS 2020

**Comment by scottaohara** [comment]
verified works with chromium edge, but does not with legacy.

There are no plans to fix issues related to legacy edge.
