### ISSUE TITLE
Empty cells in tables are skipped (Chrome, Edge)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#403]
### Summary

1. Go to https://codepen.io/jaws-test/full/KKVRVRR
2. navigate with alt+ctrl+arrow keys inside the table

### Expected result

* Correct output of empty cells as "empty" as with Firefox and IE 11
* Consistent navigation within a row or column

### Actual result

* Empty cells are skipped or
* Empty cells cause JAWS to output the end or beginning of the row or column; or
* empty cells lead to a switch to another row or column

This problem occurs in Chrome and Edge, but not with IE 11 and Firefox. 

The problem is serious and should be fixed soon

#### JAWS version and build number

JAWS 2020.2003
 
#### Operating System and version

Windows 10

#### Browser and version:

Current version of IE 11, Edge, Chrome and Firefox ESR

**Comment by frex65** [comment]
Tested using Chrome 84 and JAWS 2020.2006.12. Bug fixed
