### ISSUE TITLE
Only the first tooltip inside toolbar and heading is read in IE

### ISSUE THREAD

**Issue by ghristanov** [FreedomScientific/VFO-standards-support#41]
### Summary

1. Go to https://codepen.io/anon/pen/MOMLbr
2. Click on the "Only the first tooltip is read" title and press TAB only once. You should now be focusing the div with role="heading", where the first two buttons are located in.

### Expected result

Either none, or all tooltips inside that container are read out.

### Actual result

Only the first tooltip is read out. 

This is only happening when the elements are located inside a container with role="toolbar", which is placed inside another container with role="heading".

There are two other examples in the codepen link. One with the buttons placed directly inside the div with role="heading" and one with that div missing (only placed inside div with role="toolbar"). In the first example, both tooltips are read out and in the second - neither one. 

I would expect one of those outputs for my case - either read all tooltips or just skip them completely. 

### Example

https://codepen.io/anon/pen/MOMLbr

### Additional Information

The reason behind role="application" on the body, is explained in this issue:
https://github.com/FreedomScientific/VFO-standards-support/issues/13

#### JAWS version and build number

18.0.4350
 
#### Operating System and version

Windows 10 Enterprise
Version: 1607

#### Browser and version:

IE 11.1944.14393.0

**Comment by stevefaulkner** [comment]
@ghristanov sorry for not getting to this previously. Elements with `heading`  roles should not be focusable i.e. should not have `tabindex=0` set, this results in JAWS attempting to work out the accessible name for the element from the content as it thinks its an interactive element, which it is not. The appropriate behavior is not to announce an accessible name when a toolbar receives focus, it should be focusable though.

**Comment by scottaohara** [comment]
Closing as not a jaws bug
