### ISSUE TITLE
heading is read as clickable

### ISSUE THREAD

**Issue by 615349** [FreedomScientific/VFO-standards-support#428]
### Summary

i am on React 16.13.1

```
import { createPortal } from "react-dom";

createPortal(
    <h1>This is heading</h1>,
    document.getElementById("modal")
  );
```

the above snippet would be read as
**this is heading, heading level one, clickable**

### Expected result
heading should not be read as clickable

### Actual result
heading is read as clickable

### Additional information
Voice over, NVDA and talkback would not read it as clickable

### Example
https://codesandbox.io/s/vibrant-kowalevski-7ginb?file=/src/App.js

#### JAWS version and build number
jaws: 2019.1907.42

 
#### Operating System and version
windows 10

#### Browser and version:
chrome
84.0.4147.125

**Comment by stevefaulkner** [comment]
@615349 tested with JAWS 2020, the text in the modal is not announced as clickable. Unsure about the test case you provided as you talk about a heading being announced as clickable but there is not heading in the test case?
