### ISSUE TITLE
JAWS2018 reads entire dialog instead of header and focused element (FF 79.0)

### ISSUE THREAD

**Issue by Leuvarden** [FreedomScientific/VFO-standards-support#431]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
> 2. Click "Add Delivery Address" with JAWS2018 on.
> 3. Modal dialog is shown. 

### Expected result

> JAWS reads the header of the dialog and the focused element.

### Actual result

> JAWS reads entire dialog text: heading, field labels and buttons. 

### Example

> https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html

#### JAWS version and build number

2018.1811.30 ILM
 
#### Operating System and version

Windows 10 Enterprise. version 10.0.18362 Build 18362

#### Browser and version:

Firefox 79.0

![image](https://user-images.githubusercontent.com/16884735/91148831-fbc11380-e6c2-11ea-8522-787c6bc9c0e6.png)

**Comment by stevefaulkner** [comment]
@Leuvarden tested in JAWS 2020 and Firefox 80.0 (64-bit). When dialog is opened announces dialog name and focused element.

**Comment by Leuvarden** [comment]
Thanks for the quick response! Seems like it really was fixed in later release

**Comment by Leuvarden** [comment]
Seems like FF80+JAWS2020 still reads entire dialog 
![image](https://user-images.githubusercontent.com/16884735/93597754-38cbad80-f9c4-11ea-98f4-54b8df2f17d5.png)
