### ISSUE TITLE
Jaws reading parent element aria-label when we focus on button : Accordion

### ISSUE THREAD

**Issue by mounikaseelam** [FreedomScientific/VFO-standards-support#433]
### Summary

> I have a accordion , where accordion header has buttons as well
> the accordion header is made up of div with role button tabindex 0, and have required attributes like aria expanded etc

### Issue

>When jaws enabled and when the focus is on div jaws read as expected , but when the focus on button which is present in div with role button , jaws reading the aria-label of div even though the button has its own aria-label 

### Example

>https://www.w3schools.com/code/tryit.asp?filename=GIBFPEYV1CRD

>using Jaws 2020
>OS window 10
>browser Chrome - Version 84.0.4147.125

tested with other screen reader , the behaviour is as expected (its reading the button aria-label) except jaws
please help me out with this problem

**Comment by stevefaulkner** [comment]
@mounikaseelam you cannot have a button nested inside another button (including a role=button)

role="button" allows Flow content, but there must be no interactive content descendant. 
source: https://w3c.github.io/html-aria/#index-aria-button
```
<div class="accordion" tabindex="0" aria-label="Personal Info" role="button" aria-expanded="true" id="accordion1">
   		<h3><span class="Accordion-icon"></span><span class="title">Personal Info</span></h3>
        	<div class="headercontrol"><button type="button" role="button" aria-label="test 1">test 1</button></div>
    	<div class="headercontrol"><button type="button" role="button" aria-label="test 2">test 2</button></div>
```
        
    	
    </div>

**Comment by mounikaseelam** [comment]
sure @stevefaulkner  , i will modify the markup not to have button nested inside another button
