### ISSUE TITLE
Menus created in UIA always read as Submenus

### ISSUE THREAD

**Issue by andreas-stefik** [FreedomScientific/VFO-standards-support#436]
### Summary

> Brief description of the issue. Please list any specific steps.

Menus created using UIA do not read correctly, always saying Submenu. To reproduce, go to:

Download Quorum Studio and Install it. Be sure it is version 2.1: https://quorumlanguage.com/download.html

Open the tool and open any menu. They all say submenu. The UIA looks correct to me and both Narrator and NVDA read the menu controls correctly. JAWS is also missing ordinality and cardinality, but NVDA has this information. So far as I can tell, this is also correct in our UIA implementation.

### Expected result

I expected it to say it was a menu and to provide ordinality and cardinality.

### Actual result

JAWS says the name and the word "submenu"

### Example

Download Quorum Studio and go to any menu.

#### JAWS version and build number

Latest version on live.
 
#### Operating System and version

Windows 10, 2004, version 19041.450

#### Browser and version:

This is not a browser bug. It appears to be a bug in the UIA implementation in JAWS.

**Comment by stevefaulkner** [comment]
@andreas-stefik can you provide more information

**Comment by andreas-stefik** [comment]
I accidentally pressed save too soon when creating this bug. I apologize for that and have updated with steps to reproduce.

**Comment by stevefaulkner** [comment]
@andreas-stefik unfortunately bugs with non web UIs are not in scope of this issue tracker, @BenKeyFSI may advise you on where to file.
