### ISSUE TITLE
aria-expanded true/false status is not read by jaws when the element having role heading

### ISSUE THREAD

**Issue by mounikaseelam** [FreedomScientific/VFO-standards-support#437]
### Summary

>aria-expanded true/false status is not read by jaws when the element having role heading
> source: https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions

from the above source 

This attribute can be used with elements of the following roles: alert, alertdialog, application, article, banner, button, columnheader, combobox, complementary, contentinfo, definition, dialog, directory, document, form, grid, gridcell, group, **heading**, img, link, list, listbox, listitem, log, main, marquee, math, menu, menubar, navigation, note, presentation, radiogroup, region, row, rowgroup, rowheader, search, separator, status, tab, tablist, tabpanel, timer, toolbar, tooltip, tree, treegrid, treeitem.

`<div  tabindex="0" aria-label="Personal Info" role="heading" aria-expanded="true">
   	<h3><span class="title">Personal Info</span></h3>
        <div class="headercontrol"><button type="button" role="button" aria-label="test 1">test 1</button></div>
    	<div class="headercontrol"><button type="button" role="button" aria-label="test 2">test 2</button></div>`
</div>

### Expected result

> Jaws should read the status of aria-expanded when element is focused

### Actual result

> but Jaws not reading the  aria-expanded status

https://www.w3schools.com/code/tryit.asp?filename=GIC0YNO7MADI

Jaws 2020
OS : windows
browser: Chrome

**Comment by JAWS-test** [comment]
The reason is probably that aria-expanded is no longer allowed for headings: https://www.w3.org/TR/wai-aria-1.2/#aria-expanded

**Comment by scottaohara** [comment]
agreed.  Using a bit of the provided example code, it would be more expected to be marked up as follows:

```html
<h3><button aria-expanded="true" class="title">Personal Info</span></h3> 
```

additionally, per the sample code provided, noting that a `<h3>` is not expected to be nested within a `role=heading`, `aria-label` repeating the content of the visible text within a node is unnecessary, as is using `role=button` on a button element.
