### ISSUE TITLE
Difference in 'aria-controls' cues on aria-expanded states

### ISSUE THREAD

**Issue by devarshipant** [FreedomScientific/VFO-standards-support#44]
**Summary**

Potential gap in how instructional cues are processed by JAWS 18 - IE 11 and JAWS 18 - Edge when using aria-controls in https://test-cases.tink.uk/aria-expanded/index.html (example by @LJWatson)

Example:
1. Go to https://test-cases.tink.uk/aria-expanded/index.html
2. Tab to the button 'Tequila'
3. Activate the button

### Expected result

- Screenreader should give the acc name of the control + current state + how to activate + instructions on getting to controlled element (in this case pointer to aria-controls)

### Actual result 

- JAWS 18 / IE11 / Win 10 / 64 bit: JAWS 18 speaks 'Tequila, use JAWS key + Alt + M to move to controlled element, expanded.' 
- JAWS 18 / Edge / Win 10 / 64 bit: Does not give shortcut cues to get to controlled element, but indicates the use of spacebar to activate. 'Tequila button expanded, to activate press spacebar.'

### Example

- https://test-cases.tink.uk/aria-expanded/index.html

#### 

 
#### Operating System and version
- Win 10 / 64 bit

#### Browser and version:
- JAWS 18.0.2531 / IE 11 / IE Edge 25

**Comment by jducrot** [comment]
For what it's worth, the announcement is identical for both browsers with JAWS 20: "Tequila button expanded/collapsed. To activate press enter". To be clear this is for both IE11 and Edge on Windows 10 64 bit.
