### ISSUE TITLE
JAWS reads word 'link' for <a role='button'> in IE11

### ISSUE THREAD

**Issue by yugu0114** [FreedomScientific/VFO-standards-support#446]
### Summary

> We have <a> with role='button' but in IE 11 Jaws ignores role and adds word 'link' after reading a label.

` <a class="gwt-Anchor nc-field-html-focusable-content" href="javascript:;" 
     aria-role="button" aria-roledescription="Press enter to activate the menu." 
     aria-haspopup="true" aria-label="200 items per page" tabindex="0">200</a>`

### Expected result

> word 'link' is not read

### Actual result

> word 'button' (or in our case 'menu') is read

### Example

> https://jsbin.com/yesalejuxe/edit?html,css,output

#### JAWS version and build number
2020.2008.24 ILM

 
#### Operating System and version
Win 10

#### Browser and version:

IE: version 11.1082.18362.0/ Update versions 11.0.210 (KB4577010)

**Comment by stevefaulkner** [comment]
@yugu0114 try changing  `aria-role="button"` to `role="button"` as `aria-role` is meaningless

**Comment by stevefaulkner** [comment]
@yugu0114 I also noted you are using `aria-roledescription` which will in browsers that support it override the default role description of button, amongst other things. Suggest you don't use `aria-roledescription` this article may be helpful https://adrianroselli.com/2020/04/avoid-aria-roledescription.html Also note as you have a `href` attribute on the `<a>` you don't need `tabindex=0` as it is already focusable.
