### ISSUE TITLE
JAWS 18 precedence levels with aria-labelledby and aria-label

### ISSUE THREAD

**Issue by devarshipant** [FreedomScientific/VFO-standards-support#45]
### JAWS 18 precedence levels

> JAWS 18 speaks the value of aria-label, instead of aria-labelledby IDREFs. 

> Example:
> 1. Go to https://codepen.io/devpant/pen/GybdQq?editors=1000
> 2. Screen reader users -- in virtual cursor mode, use the headings list to navigate to 'JAWS 18 precedence levels' and tab twice to the text box control.

### Expected result

> JAWS 18 should speak the aria-labelledby IDREFs 'Set one Label set one instructions.'

### Actual result

> JAWS 18 speaks value of aria-label, 'aria-label.'

### Example

> https://codepen.io/devpant/pen/GybdQq?editors=1000

#### JAWS version and build number

JAWS 18; 18.0.2531
 
#### Operating System and version

Win 10; 64 Bit

#### Browser and version:

IE 11

**Comment by LJWatson** [comment]
I can confirm this issue with Jaws 18 in IE11, but it looks as though it's been fixed in Jaws 2018.

**Comment by devarshipant** [comment]
Thanks for checking it out @LJWatson.

**Comment by ggordon-vfo** [comment]
Verified that this continues to work properly in JAWS 2019. Closing issue.
