### ISSUE TITLE
Headers (TH) are not readout by JAWS in Tables

### ISSUE THREAD

**Issue by smuthyapu** [FreedomScientific/VFO-standards-support#460]
### Headers (TH) are not readout by JAWS in Tables

> When the focus is in a data cell of the table, pressing H is not reading out the corresponding header of the column.
> 
> Example:
> 1. Go to https://smuthyapu.github.io/THTableJAWS/TableHeaderWithTH.html
> 2. Use JAWS to traverse through the cells
> 3. Press H when the focus is in a data cell.

### Expected result

> JAWS reads out the header of the current column.
> TH should be considered as an header based on https://www.w3.org/WAI/tutorials/tables/ 
>H is the hotkey based on https://www.freedomscientific.com/SurfsUp/Quick_Keys.htm

### Actual result

>  JAWS just says "there is no header for this page".

### Example

> https://smuthyapu.github.io/THTableJAWS/TableHeaderWithTH.html

**Comment by JAWS-test** [comment]
H is for headings (h1 - h6), not for column headings (th). So everything is correct here and the issue can be closed

**Comment by smuthyapu** [comment]
Is there an hotkey to read out the content of a TH when the focus is in TD?

**Comment by JAWS-test** [comment]
JAWS has several ways to do this. Let me name just two of them:
* Navigating through the table with Ctrl+Alt+arrow keys. The row or column headers are automatically output before the cell contents
* Tab on an interactive element within a table cell: In some browsers, the column header is automatically output here as well

**Comment by stevefaulkner** [comment]
@smuthyapu with virtual focus on a data cell (`td`) you can use _Read current cell_ `CTRL+ALT+NUM PAD 5` and any associated headers (`th`) will be announced.
