### ISSUE TITLE
JAWS reads incorrect number of list items in PowerPoint

### ISSUE THREAD

**Issue by dabrams888** [FreedomScientific/VFO-standards-support#463]
### Text formatting causes JAWS to misinterpret the number of items in a list

> If the text formatting changes within a single list item, JAWS interprets it as multiple list items.  This seems to be the case regardless of whether the list is ordered or unordered.

### Expected result

> JAWS should read the correct number of list items regardless of the text formatting within each list item

### Actual result

> JAWS seems to interpret the change in format as starting a new list item

### Examples

> Example 1: JAWS reads as 2 list items (as expected)
> 1. first list item
> 2. second list item
>
> Example 2: JAWS reads as 4 list items (instead of the expected 2)
> 1. first list **item**
> 2. second list **item**

See attached file for additional test cases.
[JAWS-list-test.pptx](https://github.com/FreedomScientific/VFO-standards-support/files/5425998/JAWS-list-test.pptx)

#### JAWS version and build number

JAWS Professional 
Version 2020.2008.24
 
#### Operating System and version

Windows 10 Professional
Version 1901
OS build 18363.1139

#### User Agent and version:

Microsoft PowerPoint 
Version 2009
Build 13231.20390

**Comment by stevefaulkner** [comment]
@dabrams888 We only deal with HTML/ARIA/CSS bugs here. @BenKeyFSI can you triage/file this in the appropriate internal FSI tracker when you get a chance?
