### ISSUE TITLE
TextInput with aria-invalid="false" is read out as Invalid by JAWS

### ISSUE THREAD

**Issue by keerthanameka25** [FreedomScientific/VFO-standards-support#464]
### Summary

> I have a text input (say FirstName) with attribute aria-invalid="true" and next text input (say LastName) with attribute aria-invalid="false".
> When I TAB to FirstName, JAWS is reads as Invalid - which is expected. Now when I TAB to LastName, JAWS is reading this one also as Invalid even though aria-invalid="false"

### Expected result

> When aria-invalid="false" JAWS should not read the field as Invalid

### Actual result

> When preceding textfield has aria-invalid="true", JAWS should not read current field as INVALID.

### Example

> 1. Go to https://www.w3schools.com/code/tryit.asp?filename=GK4VUXCLKLQB
> 2. Navigate from Email Address textfield to Phone using TAB. JAWS is reading Phone field as Invalid.

### Additional Information
Tested in
Jaws 2020
OS : windows
browser: Chrome

**Comment by JAWS-test** [comment]
I cannot reproduce the problem. I have the following output with Chrome version 86.0.4240.111:

### JAWS 2020.2006 and JAWS 2008:

Email address: Edit invalid entry 
test-email
Type in text.
Phone: Edit 
040-23423421
Type in text.


### JAWS 2019.1912

Email address: Edit invalid entry 
**Invalid** test-email
Type in text.
Phone: Edit 
**end Invalid** 040-23423421
Type in text.

This means that the output is correct with both JAWS 2020 and JAWS 2019. The only problem with JAWS 2019 is that the output of "invalid" is redundant and the output of "end invalid" is superfluous.

**Comment by stevefaulkner** [comment]
Confirmed cannot reproduce in JAWS 2020

**Comment by JAWS-test** [comment]
@keerthanameka25 
The wrong output is not done with Tab navigation, but with the virtual cursor, see https://github.com/FreedomScientific/VFO-standards-support/issues/465
