### ISSUE TITLE
JAWS reads extra information  “ Insert F1 for Help” for Dropdown in IE

### ISSUE THREAD

**Issue by keerthanameka25** [FreedomScientific/VFO-standards-support#466]
### Summary

> In IE browser, if a dropdown has title attribute (used for tooltip), JAWS is reading “ Insert F1 for Help” for every option.
> Observed this behaviour only in IE browser. Working fine in Chrome.

> Example:
> 1. Go to https://jsbin.com/gihotiyefa/1/edit?html,output in IE browser
> 2. Using Alt+DownArrow key, expand the options and navigate through options using up/down arrow keys
> 3. Notice, JAWS reads out “Insert F1 for Help” for every option

### Expected result

> JAWS reads the options as "Volvo", "Saab".... just like in Chrome browser.

### Actual result

> JAWS is reading as "Insert F1 help Volvo", "Insert F1 help Saab"....

### Additional Information
Observed the issue in JAWS 2018, JAWS 2019
OS : windows
browser: Internet Explorer
Version: 11.0.10240.17394

**Comment by JAWS-test** [comment]
This problem generally occurs with elements that have a title attribute when JAWS is in application mode

**Comment by stevefaulkner** [comment]
Closing this issue as wontfix as its IE only
