### ISSUE TITLE
Announcement of text in parent when an edit box recieves focus

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/VFO-standards-support#47]
**Summary**
In the case that a parent element of an interactive element, which when focused cause JAWS to enable forms mode, results in JAWS announcing all the text content of the parent element on focus.
The cause of this appears to be the presence of an `aria-hidden=false` attribute on the parent element. When this is removed it no longer occurs.

**[Example code:](https://codepen.io/stevef/pen/xYwQao)**
```<div aria-hidden="false" class="wrong">
 Using JAWS 2018 and IE 11: Any text that is a descendent 
  <div> of an element with aria-hidden=false
    <div> will get announced as one big label for
      <div> the following text box, when the text box gets focus via the tab key.
        <div><input type="text" aria-label="and thats not right">
        </div>
      </div>
    </div> 
  </div>
</div>
```
**Steps to reproduce:** 

1. With JAWS 2018 running Go to https://s.codepen.io/stevef/debug/xYwQao in IE11
2. Once the page has loaded press the `TAB` key to focus the first `input type="edit"`
3. Listen to what JAWS announces, then press the `TAB` key again to focus the second `input type="edit" and listen to what JAWS announces.

**Expected result**
When first textbox gets focus the `aria-label` is announced:

> "and that's not right"

When second textbox gets focus the `aria-label` is announced:

> "and that's right"

**Actual result**
When first textbox gets focus

> "Using JAWS 2018 and IE 11: Any text that is a descendant
> of an element with `aria-hidden=false`
> will get announced as one big label for
> the following text box, when the text box gets focus via the tab key. "
 
is announced, then the
` aria-label` is announced:

> "and that's not right"

When second textbox gets focus the `aria-label` is announced:

> "and that's right"

**Additional Information**
JAWS 2018
Windows 10
Internet Explorer 11

**Note:** The cause can only be understood by reviewing the FSDOMserver output as the accessibility tree exposed in IE 11 is correct.

**Comment by LJWatson** [comment]
I wonder if this is a collision between IE supporting ```<div aria-hidden="false" style="display:none;">Hidden visually</div>``` as a mechanism for hiding content visually but not from screen readers, and the accessible name computation?

**Comment by stevefaulkner** [comment]
Filed internally as Bug 99327 - Announcement of text in parent when an edit box receives focus

**Comment by TPGJRogers** [comment]
Issue is marked IE11. Closing.
