### ISSUE TITLE
select required-information is not announced after an item has been selected

### ISSUE THREAD

**Issue by MichaelKetting** [FreedomScientific/VFO-standards-support#486]
### Summary

1. Open the attached test page. 
2. Navigate through the individual listbox using the TAB key and the virtual PC cursor.
3. Select the first item in each listbox.

### Expected result

- Every listbox has 'required' announced when no item is selected (2)
- Every listbox has 'required' announced after the first item has been selected (3)

### Actual result

Chrome & Edge:
For listboxes, 'required' is not announced after an item has been selected. When usign TAB, 'required' is announced for all listboxes.

Firefox:
For listboxes supporting multi-select, 'required' is only announced if no has been selected.
For listboxes supporting only single-select, 'required' is announced regardless of the selection state.
When usign TAB, 'required' is announced for all listboxes regardless of the selection state.

### Example
[TestPage.zip](https://github.com/FreedomScientific/VFO-standards-support/files/5835025/TestPage.zip)

### Additional Information
This is relevant when using multi-select to inform the user that it would not be valid to deselect all items and with single-select to provide a consistent experience while filling out the form or in cases when the null-option is explicitly provided as part of the options list.

#### JAWS version and build number
JAWS 2021.2012.48
JAWS 2020.2012.13
JAWS earlier versions probably had the same behavior

 
#### Operating System and version
Windows 10 v2004, OS Build 19041.685

#### Browser and version:
Microsoft Edge 87.0.664.75
Google Chrome 87.0.4280.141
Mozilla Firefox 84

**Comment by JAWS-test** [comment]
If I understand correctly, the problem does not occur in form mode (tab navigation), but only when reading linearly with the virtual cursor. I am unsure if it is a problem then. With the virtual cursor generally less information is output. However, as soon as the listboxes are interacted with, the correct output occurs (i.e. after switching to form mode)

**Comment by MichaelKetting** [comment]
@JAWS-test thank you for the quick response. 

Correct, this inconsistency s only occurring in browse mode, not form mode. I cannot speak to whether this is sufficient for users that require a screenreader, but it is at least inconsistent/unexpected behavior. The problematic aspect here is, that such inconsistencies almost always result in additional effort (quality assurance and project maangement) when accessibility features are developed due to first discovering this inconsistency and then analyzing the problem, reporting it, and discussing it between project manager and the customer.

It is acceptable for me at this point, if this issue classified as a documented and intended behavior in JAWS (or a bug that won't be fixed), so long as it is clear that it is not something the web developer must consider (and work-around) given the behavior is determined by the screenreader implementation.

**Comment by JAWS-test** [comment]
@MichaelKetting 
I am not from Freedom Scientific, so I cannot say if this is classified as a JAWS bug. I have only presented my private opinion. Of course the inconsistency is annoying and I am in favor of fixing it. Unfortunately, there is no specification that dictates what information must be perceptible with the virtual cursor. That's why it's hard to judge if there is a bug here. If it is a bug, it is also questionable whether a work around needs to be found. According to WCAG, aria-required and required were used correctly. However, the attributes cannot be relied upon if they are not [accessibility supported](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance#uc-accessibility-support-head). As a WCAG tester, I wouldn't consider this a problem, since the correct output occurs in form mode.

**Comment by accessiblecohn** [comment]
All items in this page speak "required" in JAWS 2022.2204.20 in both Edge Version 101.0.1210.53Fixed  and Firefox Version 100.0.2.
