### ISSUE TITLE
No support for ARIA table roles in Edge

### ISSUE THREAD

**Issue by LJWatson** [FreedomScientific/VFO-standards-support#49]
### Summary
Jaws does not recognise the ARIA `table`, `row`, `columnheader`, `rowheader`, and `cell` roles in Edge.

1. Navigate to the [test case](http://design-patterns.tink.uk/aria-tables/), which contains two tables (one ARIA and one HTML)
2. Use the `t` shortcut key to move between tables
3. Use the arrow keys to move to the first table, then standard table navigation commands to interact with it (control alt left/right/up/down)

### Actual result
Jaws does not recognise the first (ARIA) table, and standard table navigation commands do not work.

### Example
http://design-patterns.tink.uk/aria-tables/

#### JAWS version and build number
Jaws 2018.1801.81

#### Operating System and version
Windows 10 64bit

#### Browser and version:
Edge 41

**Comment by stevefaulkner** [comment]
Given that Edge in its current state [will not continue to be developed](https://twitter.com/stevefaulkner/status/1070761434450141185) closing this as won't fix
