### ISSUE TITLE
JAWS  announce a table with role="presentation"

### ISSUE THREAD

**Issue by eguen** [FreedomScientific/VFO-standards-support#505]
### Summary

Table with a role=presentation contains elements. When you navigate with [TAB] to the first element JAWS reads out table, it's row and column, then the last element and at the end the first element.

### Expected result

We would expect JAWS to annouce the first element and then the last one.

### Actual result

JAWS reads out table column, row, the last element, the first element.

### Example

https://codepen.io/eguenther/pen/RwoeWzw

**Steps to reproduce:**

1. Start the url  
2. Click on the button "Start"
3. Navigate with [TAB] to the first element "English"

**JAWS reads out:**

Start
Button
To activate press Enter.
table
Column 1, Row 1
Test 
column 1 row 1
Englisch Button 
Content Language
To activate press Enter.

#### JAWS version and build number

2021.2102.34 ILM
 
#### Operating System and version
Windows 10

#### Browser and version:
Version 89.0.4389.72 (Offizieller Build) (64-Bit)

**Comment by JAWS-test** [comment]
I am not sure if this is really a JAWS bug. I rather think it is a bug of Chrome because in Chrome certain tables are transmitted to the Accessibility API with role=presentation as table

**Comment by eguen** [comment]
Thanks for the quick response. I am sorry, I sent the link to the wrong example. The issue can be reproduced here: https://codepen.io/eguenther/pen/dyOKpdz

**Comment by JAWS-test** [comment]
In this example the cause is the tabindex=-1 at the table. This makes the table focusable and role=presentation is ignored by Chrome. This is not a JAWS bug, but a problem of Chrome or the ARIA specification.

**Comment by eguen** [comment]
Thanks for the quick reponse and analysis!
