### ISSUE TITLE
Screen reader(JAWS) focus is not moving further after selecting the list items in the list box control while navigating using down arrow mode/browse mode. 

### ISSUE THREAD

**Issue by sharathvuppla** [FreedomScientific/VFO-standards-support#524]
Test Environment:
OS: Windows 10 version 20H2 (OS Build 19042.804)
Browser: Chrome Version 88.0.4324.190
URL: https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
Screen readers: JAWS 2021.2012.48.400

Repro Steps:
Step 1: Enable JAWS and Navigate to the above URL in the latest chrome 
Step 2: Navigate to "Basic uncontrolled example" and select list item. Verify whether JAWS focus is moving further or not. 

Actual Result:
Screen reader(JAWS) focus is not moving further after selecting the list item in 'Basic uncontrolled example' control while navigating using down arrow mode.
Ex: After selecting the list item in the 'Basic uncontrolled examples'  list box, on pressing down arrow JAWS focus is moving within the focus area list box only. Not moving further. 

Expected Result:
Screen reader(JAWS) focus should move further after selecting the list item in 'Basic uncontrolled example'  control while navigating using down arrow mode.
Ex: After selecting the list item in the 'Basic uncontrolled example'  list box on pressing the down the arrow key JAWS focus should move to the next control.

**Comment by JAWS-test** [comment]
This is not a bug. JAWS is in forms mode when a form element, such as a dropdown, is focused and operated on. To exit form mode, you can press ESC, for example. As long as JAWS is in form mode, it is not possible to navigate using the arrow keys. This is a basic principle of operation with any screen reader.
