### ISSUE TITLE
Jaws in browse mode - when the focus is on div with role tabpanel - just reading the label of it , but not mentioning like it is a tabpanel

### ISSUE THREAD

**Issue by mounikaseelam** [FreedomScientific/VFO-standards-support#527]
### Summary

> Jaws in browse mode - when the focus is on div with role tabpanel - just reading the label of it , but not mentioning like it is a tabpanel
> 
> Example:
> 1. Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html

### Expected result

> jaws should read it as tabpanel including label 

### Actual result

> Jaws just reading a label 

### Example

> https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html

**Comment by stevefaulkner** [comment]
@mounikaseelam Not all semantics are vocalized, it appears this is one of those cases.

**Comment by JAWS-test** [comment]
@stevefaulkner If it's a "feature request", it shouldn't be closed, right? Otherwise it will probably never be processed
