### ISSUE TITLE
ESC (ESCAPE) not closing collapsible listbox (dropdown) on first time 

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/VFO-standards-support#528]
### Summary

 Example:
 1. Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html
2. navigate into example 
3. open the dropdown
4. press ESC key to close dropdown 

### Expected result
Dropdown is closed

### Actual result
Dropdown is not closed, only JAWS is switch into Virtual Cursor mode 
What I remember JAWS was not switching into Virtual cursor mode after presses ESC key. Is it new functionality of JAWS? because I could not find it in the JAWS keyboard shortcuts... 

Output of JAWS narration:
```
Choose an element: Americium button menu 
Choose an element: List box 
Americium 
3 of 26
To move to an item press the Arrow keys.
Curium 
4 of 26
virtual PC Cursor
```

### Example
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html

#### JAWS version and build number
2021.2103.174 ILM

 
#### Operating System and version
Win 10 Enterprise
10.0.19043 build 19043

#### Browser and version:
Chrome
Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by JAWS-test** [comment]
This is not a new problem, it also occurs with older JAWS versions. ESC has always been the JAWS key to exit forms mode. This is also true for an HTML dropdown (select element).  However, ESC on the select element causes the form mode to be exited and the list to be closed. Why this doesn't work with the ARIA listbox, I don't know. It may even be a bug in the ARIA example. However, pressing ESC again will close the list. 

I would not consider it a bug, but a known JAWS functionality.

**Comment by kolaps33** [comment]
Hello @JAWS-test 

I was debugging dropdown in this library
https://fluentsite.z22.web.core.windows.net/0.56.0/components/dropdown/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#types-dropdown

where I can reproduce the same issue. 

I figured out during debugging that we are not able to close list because we are not receiving event when JAWS exits forms mode. 
So maybe JAWS stops send event when switches to forms mode.
