### ISSUE TITLE
JAWS not reading the position of the items even when role "listbox" and "option" is provided in HTML . Also its not reading state (selected/non-selected) even when "aria-selected" is added in the HTML.

### ISSUE THREAD

**Issue by DeepakGupta3101** [FreedomScientific/VFO-standards-support#53]
### Summary

> Brief description of the issue. Please list any specific steps.
> JAWS is not reading the position of the items in the listbox even when role="listbox" is provided on the conatiner and role="option" is provided to the child elements in the listbox container in the HTML markup.
>Also JAWS is not reading the state of the button (Selected/ Non-Selected) even when attribute "aria-selected" is provided in the HTML markup.

### Expected result

> JAWS should read the position of the items in the listbox container like ( 1 of 4, 2 of 4, etc..) and should read "selected" when **aria-selected="true"** and "non-selected" when **aria-selected="false"**

### Actual result

> It does not reads anything, nor the position nor the state (Selected/ Non-Selected).

### Example

> 	
<div class="Properties-Container" **role="listbox"**>
		<div ng-repeat="section in controller.secList" class="Properties-SectionList">
			<div ng-repeat="section in controller.secList" ng-if="$parent.$index === $index"
				 tabindex="-1" 
ng-click="controller.handleControlLayoutClick(section,(section.secColType > controller.sectionType))" mscrm-action-on-select aria-label="{{section.displayName}}"
 **role="option"** **aria-selected="{{controller.checkControlLayout(section)}}**">
				<div class="{{section.icon}}"></div>
			</div>
			<div class="Properties-Formatting-Section" ng-if="!$parent.$last"></div>
		</div>

#### JAWS version and build number
Version 2018 (18.0.2944)

 
#### Operating System and version
Windows 10

#### Browser and version:
IE11

**Comment by stevefaulkner** [comment]
@DeepakGupta3101 a test case is needed, can you please provide on?

**Comment by DeepakGupta3101** [comment]
<div class="Properties-Container" **role="listbox"**>
		<div ng-repeat="section in controller.secList" class="Properties-SectionList">
			<div ng-repeat="section in controller.secList" ng-if="$parent.$index === $index"
				 tabindex="-1" 
ng-click="controller.handleControlLayoutClick(section,(section.secColType > controller.sectionType))" mscrm-action-on-select aria-label="{{section.displayName}}"
 **role="option"** **aria-selected="{{controller.checkControlLayout(section)}}**">
				<div class="{{section.icon}}"></div>
			</div>
			<div class="Properties-Formatting-Section" ng-if="!$parent.$last"></div>
		</div>

**Comment by stevefaulkner** [comment]
Hi @DeepakGupta3101 thanks, but that is not helpful, what is needed is a working test case where the issue is evident, such as a codepen or link to a site where it occurs.

**Comment by DeepakGupta3101** [comment]
Hi Stevefaulkner,
Please find below the link for ARIA Guidelines.
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/combobox/aria1.1pattern/listbox-combo.html

We have examples in this list where we can verify that even though we have role="listbox" and "option" present, JAWS does not reads the position.

**Comment by stevefaulkner** [comment]
@DeepakGupta3101 This is a bug in IE, the `setsize` and `posinset` properties are not provided in the accessibility API information in Internet Explorer, these properties convey option position and number of options to AT. You will need to explicitly set the [`aria-setsize`](https://www.w3.org/TR/wai-aria-1.1/#aria-setsize) and [`aria-posinset`](https://www.w3.org/TR/wai-aria-1.1/#aria-posinset) attributes to expose this information in IE

**Comment by srm985** [comment]
@stevefaulkner I know this issue was marked closed, but I didn't see anyone confirming this as a functioning work around. Have you tested this and proven it as a work around?

**Comment by LordOfTheStack** [comment]
Happens in chrome too, even with the aria-setsize and aria-posinet provided. In JAWS17 it seems to read out "unselected" but not "selected" and in JAWS2018 it reads neither. The workaround I used was to additionally set "aria-checked=true" and that was read aloud correctly by JAWS (though obviously it states checked, rather than selected)

**Comment by nisith-panda** [comment]
ListBox position of the option is not reading by JAWS in Fire Fox
