### ISSUE TITLE
When using react-window JAWS repeats instruction message in the listbox/tree on each item

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/VFO-standards-support#531]
### Summary

Wen using react-window JAWS repeats instruction message in the listbox on each item. 

Example:
1. Go to example: https://dv6fv.csb.app/
2. Navigate to the listbox "Item0"
3. Press TAB key to navigate to the next item (there is no up/down arrow key support to navigate through the listbox, but for purpose of reproduce of the bug TAB key reach the same behavior)
4. Press TAB key to navigate to the next item 
5. Observe JAWS narration after each item 

### Expected result
JAWS should narrates the instruction message "To move to an item press the Arrow keys." only once, when user navigate to the listbox. 

### Actual result
JAWS narrates message "To move to an item press the Arrow keys." witch each item in the listbox. 
JAWS output:
Item 0  
1 of 5
To move to an item press the Arrow keys.
Item 1  
2 of 5
To move to an item press the Arrow keys.
Item 2  
3 of 5
To move to an item press the Arrow keys.

### Comment 
The same behavior I was able to reproduce when there was used role="tree" structure instead of role="listbox". Only instructin message was different, but it was happening on each role="treeitem".
In the example is used react library:
https://react-window.vercel.app/#/api/FixedSizeList

### Example
Example: https://dv6fv.csb.app/
Example with source code: https://codesandbox.io/s/sleepy-chatelet-dv6fv?file=/index.js

#### JAWS version and build number
reproduced with both JAWS :
2020.2006.12
2021.2103.174
 
#### Operating System and version
Windows 10 Enterprise 19043

#### Browser and version:
reproducible with both:
Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)
Firefox 89.0 (64-bit)

**Comment by stevefaulkner** [comment]
@kolaps33 I have looked into this, the issue appears to be that the element with `role=listbox` is not focusable, secondarily 2 children of the `listbox` are `div` wrappers. These can be exposed as `role=group` and are taken into account by JAWS when the children of certain composite control roles such as `listbox`.

The fix for the above is as per your example:

**current code:**
```
<div role="listbox">
<div class="List" style="position: relative; height: 300px; width: 300px; overflow: auto; will-change: transform; direction: ltr;">
<div style="height: 100000px; width: 100%;">
<div role="option" tabindex="0" class="ListItemOdd" style="position: absolute; left: 0px; top: 300px; height: 100px; width: 100%;">Item 0</div>
...
```
**Recommended code:**
```
<div>
<div class="List" style="position: relative; height: 300px; width: 300px; overflow: auto; will-change: transform; direction: ltr;">
<div style="height: 100000px; width: 100%;"  role="listbox" tabindex="0">
 <div role="option" tabindex="0" class="ListItemOdd" style="position: absolute; left: 0px; top: 300px; height: 100px; width: 100%;">Item 0</div>
...

-Or-

<div role="listbox" tabindex="0">
<div role="none" class="List" style="position: relative; height: 300px; width: 300px; overflow: auto; will-change: transform; direction: ltr;">
<div role="none" style="height: 100000px; width: 100%;">
<div role="option" tabindex="0" class="ListItemOdd" style="position: absolute; left: 0px; top: 300px; height: 100px; width: 100%;">Item 0</div>
...
```
