### ISSUE TITLE
Icons based on Unicode characters are not output as graphics

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#534]
### Summary

1. Go to https://codepen.io/jaws-test/pen/abJqgJM
2. Read the line: "This is a printer!"

### Expected result
Icons are output as graphics

Even better if there was an ARIA role for icons (see https://github.com/w3c/aria/issues/1088)

### Actual result
Icons are not output as graphics but as text

See also: https://github.com/w3c/css-a11y/issues/17#issuecomment-850935211

#### JAWS version and build number
current and older JAWS version
 
#### Operating System and version
Windows 10

#### Browser and version:
current and older versions of Chrome, Firefox, Edge, IE 11

**Comment by stevefaulkner** [comment]
@JAWS-test unicode icons have a role of text in the acc tree, therefore JAWS is conveying what it sees. If the browser accessibility tree exposed them as images but JAWS was not then it would be a JAWS issue.
