### ISSUE TITLE
Position in tree is not always announced

### ISSUE THREAD

**Issue by gdkraus** [FreedomScientific/VFO-standards-support#535]
### Summary

When navigating a tree with the VPC off, the position in the tree is not always announced. The aria-posinset and aria-setsize are set correctly, but JAWS only announces the position information the first time you enter a new level in the tree.

### Expected result

I expected JAWS to always announce the position in the tree as X of Y when I move to a role="treeitem".

### Actual result

JAWS only announces X of Y when transitioning to a new level. For example, going to the next level branch in a tree, the X of Y is read when I land on the first item, but when I arrow down to the second item in the branch no position information is announced.

### Example

https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-1/treeview-1b.html

#### JAWS version and build number

JAWS 2021.2103

#### Operating System and version

Windows 10

#### Browser and version:

Chrome 90

**Comment by stevefaulkner** [comment]
@gdkraus unclear why this is a bug, it appears more to be a feature to reduce the amount of noise announced. Besides there is no requirement on what information is conveyed to users by screen readers.

**Comment by gdkraus** [comment]
@stevefaulkner, JAWS announces position information for all items in [Menu Button](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html), [Menubar](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html), and [Listbox](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-scrollable.html). It seems like providing this information for trees would be an analogous level of support.
