### ISSUE TITLE
JAWS 18 and later doesn't recognize HTML5 footer landmark

### ISSUE THREAD

**Issue by JavierDorado** [FreedomScientific/VFO-standards-support#55]
### Summary
In Internet Explorer 11 and Mozilla Firefox ESR 52.6 JAWS 18 and JAWS 2018 (1802.78) doesn't recognize the footer landmark when navigating in virtual viewer.
1. Create a simple HTML or visit a site with a footer landmark.
2. Navigate the document with IE 11 or Firefox ESR with up / down arrow.

### Expected result
JAWS should identify the footer landmark and present it like contentinfo role.

### Actual result
JAWS doesn't present this landmark except in the list of landmarks JAWS + CTRL + r command.

#### JAWS version and build number
2018.1802.78

 
#### Operating System and version
Windows 7 

#### Browser and version:
Internet Explorer 11 and Mozilla Firefox ESR 52.6

**Comment by stevefaulkner** [comment]
@JavierDorado have a read of this recent comment on issue https://github.com/FreedomScientific/VFO-standards-support/issues/35#issuecomment-369780923 It may explain what you are experiencing.

**Comment by StommePoes** [comment]
Yeah, I get the same thing-- I get a "stop" for each landmark but what's weird is when contentinfo is announced and when it isn't: this seems entirely dependent on what's inside.

A `<footer role=contentinfo>` with only text inside it will, in JAWS and IE, announce the contentinfo... but not if there is a list as the first child. In that case, the "r" shortcut will stop there but announce the first list item.  That's kinda weird and unexpected, though I doubt it'll stop anyone from figuring out a page.

Same with banner, where sometimes one can hear they are in a banner, but not if for example the first thing inside is a nav.

**Comment by ggordon-vfo** [comment]
This was fixed as of JAWS 2018 March 2018 update. Fix also applies to JAWS 2019.
