### ISSUE TITLE
JAWS2018 Virtual Cursor Verbosity when set to default (Medium) ignores explicitly named regions and landmarks

### ISSUE THREAD

**Issue by accdc** [FreedomScientific/VFO-standards-support#57]
In JAWS2018, the Virtual Cursor Verbosity option was added to suppress the announcement of landmarks and regions on web pages, where only if set to High would these particular landmarks and regions be announced to users.

It makes sense to add general landmarks and regions that have no labels to the High category, as well as HTML5 elements that map to the same roles in the accessibility tree, but it doesn't make sense to add any landmarks or regions that are explicitly named using aria-label or aria-labelledby to this category, because it makes them impossible for users to discover without having to explicitly set this setting in advance.

Many sites are now using named regions for instance to convey critical page components including breadcrumb navigation regions, carousel regions, visual map regions, and within the APG 1.1 github archive for Accordions the use of named regions to convey dynamic accordion sections which is critical when nested accordions are combined; in which case it is impossible to determine the boundaries of each region if all of these landmarks and regions are suppressed by JAWS by default.

I suggest that all landmarks and regions that are explicitly named with aria-label or aria-labelledby be automatically included within the Virtual Cursor Verbosity category of Medium so the automatic accessibility provided by these features will not be hidden by general JAWS users who may be unaware that this setting even exists.### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Go to http://www.google.com
> 2. Shift-Tab back to the About link

### Expected result

> What did you expect to happen?

### Actual result

> What actually did happen?

### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

**Comment by stevefaulkner** [comment]
@accdc thanks Bryan, I agree that exposing regions, with accessible names, by default makes good sense. Will file a bug internally.

**Comment by LJWatson** [comment]
I'd actually like to see all landmarks included when VC verbosity is set 
to medium.

**Comment by TPGJRogers** [comment]
Issue was forwarded to and considered by Freedom Scientific as a suggestion for improvement. If you believe this issue should receive further consideration as an improvement, please [submit the suggestion via this form.](https://support.freedomscientific.com/Forms/QualityContact) Closing.
