### ISSUE TITLE
Button role and keyboard interactions not working when leaving an iframe in Chrome and Edge

### ISSUE THREAD

**Issue by mberrisford** [FreedomScientific/VFO-standards-support#578]
### Summary

1. Tab trough a webpage that contains an iframe with interactive content such as a form (see attached example files).
2. Once you leave the iframe, and there is a button as the next element, it is not announced as a button and it cannot be triggered using enter/space key.

### Expected result

1. The button is role announced as "button".
2. You can press enter or space to activate it.

### Actual result

1. The name of the button is announced but the role of "button" is not 
2. You cannot press Enter/Space to activate it.

### Example

See attached zip file containing index.html and iframe.html. 
[JAWS_iFrame_Issue.zip](https://github.com/FreedomScientific/VFO-standards-support/files/7280713/JAWS_iFrame_Issue.zip)

### Additional Information

Seems to be a JAWS/Chrome/Edge specific issue. Works as expected with the following SR/Browser combinations:

- JAWS 2021 and Firefox
- JAWS 2021 and IE11
- NVDA 2021 and Chrome
- NVDA 2021 and Firefox
- NVDA 2021 and IE11

#### JAWS version and build number

- JAWS 2021.2107.12
- Also tested with 2020.2012.13 with the same results
 
#### Operating System and version

- Windows 10 Build 19042

#### Browser and version:

- Chrome 94.0.4606.61 (Official Build) (64-bit)
- Microsoft Edge 94.0.992.38 (Official build) (64-bit)

**Comment by JAWS-test** [comment]
I can confirm the problem. The problem occurs independently of the iFrame content (tested with input field, button, without interactive elements), i.e. independently of the form mode of JAWS

**Comment by joe-watkins** [comment]
This issue appears to still be an issue. Same experience noted by @mberrisford found with:

JAWS: `2022.2206.9`
Chrome: `103.0.5060.66` 

This a Chromium thing?
