### ISSUE TITLE
role=form; inconsistent behavior with JAWS18 and NVDA 2017

### ISSUE THREAD

**Issue by devarshipant** [FreedomScientific/VFO-standards-support#61]
### JAWS18 (IE11) associates aria-labelledby reference with every form control. NVDA 2017 does it with the first control.

> JAWS18 should only associate the aria-labelledby reference with the first control.
> JAWS18 interaction with role=form is similar to fieldset / legend. Should it be?

> Example:
> 1. Go to https://codepen.io/devpant/pen/YaYBgd
> 2. Tab to Name 
> 3. Tab to Address 

### Expected result

> JAWS18 should only associate Group A with Name.

### Actual result

> JAWS18 (IE11) associates Group A with Name when Name control has focus.
> JAWS18 (IE11) associates Group A with Address when Address control has focus.

### Example

> https://codepen.io/devpant/pen/YaYBgd

**Comment by devarshipant** [comment]
Hi @stevefaulkner,

what does JAWS 2018 says when focus is on Name and Address? NVDA 2017 and JAWS18 announce the controls differently.
1. "Group A Name" and "Address" is the screen reader output with NVDA2017.
2. "Group A Name" and "Group A Address" is the screen reader output with JAWS18.

**Comment by stevefaulkner** [comment]
This is what I get with JAWS 2018, you may well be getting a different result with JAWS18, but it is not present in JAWS 2018 version 1804.32 with IE11
JAWS output (and keystrokes used):
1. "role form test case, heading level 1"
2. press down arrow
3. "Group A Form"
4. press Tab
5. "Group A, Name Edit, Type in text."
6. press Tab
7. "Address, Edit"

**Comment by devarshipant** [comment]
That helps. Steps 5 and 7 in your testing confirm the behavior I am expecting. The first control is associated with the aria-labelledby IDREF, not the second control.
thanks!

**Comment by wittjeff** [comment]
With IE11. 0.9600.18977CO and Jaws 18.0.4350 I can confirm the overly
verbose output as you describe.

**Comment by ggordon-vfo** [comment]
Fixed as of JAWS 2018.
