### ISSUE TITLE
JAWS 18 not reading the role for HTML select box in chrome with tab / shift tab navigation

### ISSUE THREAD

**Issue by Rasubra8** [FreedomScientific/VFO-standards-support#63]
JAWS 18 is not reading the role for HTML select box while navigating with tab / shift tab. But, announcing the role in in arrow key navigation and in Quick navigation (F)and (C). When tested with FF 52 and IE 11 the role is announced both in tab navigation and also arrowkey and quick navigation. 
JAWS version: 18
Chrome 65
Windows7

### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
<label for ="s"> Choose your class </label>
<select required id="s">
<option value="Class 1"> Class 1 </option>
<option value="Class 2"> Class 2 </option>
<option value="Class 3"> Class 3 </option>
<option value="Class 4"> Class 4 </option>
<option value="Class 5"> Class 5 </option>
<option value="Class 6"> Class 6 </option>
<option value="Class 7"> Class 7 </option>
<option value="Class 8"> Class 8 </option>
<option value="Class 9"> Class 9 </option>
<option value="Class 10"> Class 10 </option>
</select>
### Expected result
JAWS should read the role i.e (Combo box)

> What did you expect to happen?

### Actual result

> What actually did happen?

### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

**Comment by stevefaulkner** [comment]
@Rasubra8 Hi You need to provide a code example that exhibits the issue you are experiencing.

**Comment by Rasubra8** [comment]
![image](https://user-images.githubusercontent.com/28350461/38429315-a62fdafa-39db-11e8-9d21-791c0068950a.png)

**Comment by Rasubra8** [comment]
Added the screen shot with code for reference.

**Comment by Rasubra8** [comment]
Any update please?

**Comment by Rasubra8** [comment]
https://codepen.io/rameict/pen/yjBeJy``

**Comment by Rasubra8** [comment]
Hi I have pasted the codepen link, Request you to check this


[https://codepen.io/rameict/pen/yjBeJy](url)

**Comment by stevefaulkner** [comment]
@Rasubra8 tested with JAWS 2018 and Chrome 65, using a version of your [test case](https://codepen.io/stevef/pen/QrLNRa) the combobox role was announced when navigated to using the tab key.

**Comment by Rasubra8** [comment]
Thanks for the response.
Yes, it is working in jaws 2018. But, in jaws 18, the same is not working. The combo box role is not announced in tab / shift tab navigation. Can this be a possible jaws 18 bug?

**Comment by stevefaulkner** [comment]
@Rasubra8 yes, but it is fixed in JAWS 2018.
