### ISSUE TITLE
Landmark regions only show up if present on page load

### ISSUE THREAD

**Issue by DavidMacDonald** [FreedomScientific/VFO-standards-support#65]
### Summary

Lazy loads and JS generated pages may have landmarks that don't show up in JAWS

### Example:
Will add a website after it goes public, on staging server until next week.
Open a list of landmarks Insert+control+R

### Expected result
should have landmarks (main, contentinfo etc.

### Actual result

No Landmarks in list

#### JAWS version and build number
JAWS 2018 but all versions do this.

**Comment by stevefaulkner** [comment]
@DavidMacDonald thanks dave, awaiting the example to test and also what browser(s)?

**Comment by ggordon-vfo** [comment]
Example never provided; closing issue.
