### ISSUE TITLE
JAWS reads both "aria-label" and "title" attribute for <button/>

### ISSUE THREAD

**Issue by hrishavkmr** [FreedomScientific/VFO-standards-support#654]
### Summary

> JAWS reads both "aria-label" and "title" attribute for \<button\> element. For example, If HTML looks like this
 ```html
<button aria-label="test" title="title">Button</button> 
```
Then, JAWS narrates it as "test button title"(\<aria-label\> button \<title\>), but it should just read it as "test button"(similar to windows narrator app).

> 
> Example:
> 1. Create a button with "aria-label" and "title" attribute set.
> 2. Focus JAWS on the button

### Expected result

>  JAWS should read button as "test button"

### Actual result

> JAWS reads button as "test button title"

### Example

> https://codepen.io/hrishavkmr/pen/PoRmGME

#### JAWS version and build number

JAWS J2022.2206.9
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 103

**Comment by JAWS-test** [comment]
This is not a JAWS bug. If it were otherwise, i.e. if title were not output, it would be a JAWS bug. aria-label is the label (Accessible Name), title is the description (Accessible Description) and both must be output independently.

If you do not want to hear descriptions, you can disable them in the JAWS settings.

**Comment by hrishavkmr** [comment]
@JAWS-test Can you please share the steps to disable the "description"?

**Comment by JAWS-test** [comment]
INS+6 > Speech Verbosity > Expert

**Comment by rr-it** [comment]
The following does not work with NVDA.

For web-developers:

~If the `title`-attribute is somehow necessary, but should not be announced, then just set an empty `aria-description=""`.~

```
<button
  aria-label="Some action"
  aria-description=""
  title="This is ignored as aria-description is set."
>This is ignored as aria-label is set.</button>
```

~Readout: " 'Some action' button"~

Also see:
https://w3c.github.io/aria/#aria-description
https://html.spec.whatwg.org/multipage/dom.html#attr-title

----

Using a null character hack actually works with NVDA:

```html
<button
  aria-label="Some action"
  aria-description="&#0;"
  title="This is ignored as aria-description is set."
>This is ignored as aria-label is set.</button>
```
