### ISSUE TITLE
description lists with child divs not recognised as lists

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/VFO-standards-support#66]
**Example:**
with JAWS 2018 running
1. go to https://s.codepen.io/stevef/debug/GxwaoP
2. navigate to lists using the L key 

**Expected result**
JAWS navigates to case 1, 2 and 3 description lists and identifies as lists

**Actual result**
JAWS only navigates to the case 2 for which the `dl` has no `div` children and only identifies 1 list.

**Additional Information**
The allowed children for the [`dl` element](https://www.w3.org/TR/html52/grouping-content.html#the-dl-element) has recently changed to allow div wrappers for `dt/dt` elements

- JAWS 2018 1803.54 (march 2018)
- Windows 10
- Firefox ESR 52.7.3 (64-bit)

**Comment by stevefaulkner** [comment]
**note:** JAWS recognises case 1 and 3 as lists in the FSDOM server output but adds `fsExclude="1"` to the  lists containing the `div` children

`<domnode inType="List" fsType="85" fsTag="DL" fsID="ffff0ce6" fsExclude="1" fsStructural="1" fsOffset="41" fsEnd="174" fsLeft="12" fsRight="1908" fsTop="289" fsBottom="409" id="dl-01">`

**Comment by stevefaulkner** [comment]
Actually its not so cut and dried, retesting in Chrome Version 65.0.3325.181 (Official Build) (64-bit) JAWS 2018 handles all cases the same, and recognizes all as lists, so may be something todo with the way Firefox and chrome differ in how they convey the `dl/dt/dd` semantics...

**Comment by lamador** [comment]
Retested using Firefox 74.0 (64-bit) and JAWS 2020.2003.13.  JAWS navigates to case 1, 2, 3 and 4 description lists and identifies as lists.
