### ISSUE TITLE
JAWS 18.0.4534 not reading modal dialog 

### ISSUE THREAD

**Issue by jrautio** [FreedomScientific/VFO-standards-support#67]
### Summary

> 1. Windows 10 -  IE11 - 
> 2. select Select/Deselect link

read the first control form with cursor focus

spoke with technical staff at CSUN,  they stated they are having the same issue.

**Comment by jrautio** [comment]
When I select a link that opens a modal dialog with cursor focus on the first control form, JAWS is not reading the control form or any other control forms on the modal.

Web application / IE11 / Windows 10 /
JoAnn Rautio

**Comment by jrautio** [comment]
This is not a public site. Thus, you cannot access the application.


Please close


JoAnn Rautio

**Comment by ggordon-vfo** [comment]
Issue author requested that the bug be closed.
