### ISSUE TITLE
Salesforce-Vlocity typeahead element (<input/>) not registering as "required" in FormField DialogBox

### ISSUE THREAD

**Issue by soehlerSF** [FreedomScientific/VFO-standards-support#676]
### Summary

Typeahead/autocomplete/editcombo input elements tagged as "required" (either by `required` attribute or `aria-required="true"` attribute) are correctly shown as "required" by JAWS speech engine, but are incorrectly **not showing** as "required" in the JAWS FormField dialog box (Insert+F5).  Typically, required fields are indicated with an asterisk in FormField dialog box. Typeahead/autocomplete/editcombo <input/> required elements shown in the test case below do not have asterisks in FormField, whereas they should.

Testing shows that the JAWS speech engine, Mac Voiceover, NVDA speech engine, and NVDA FormField dialog box working correctly in this matter, so this issue is likely a bug isolated to just the FormField functions of JAWS.

### Expected result

Expected typeahead/autocomplete/editcombo <input/> required elements to be shown with asterisks in the FormField dialog box (invoked by Insert+F5).

### Actual result

Typeahead/autocomplete/editcombo <input/> required elements are shown without asterisks in the FormField dialog box. Screenshot shown at bottom of ticket.

### Example

1. Go to the following publicly-facing sandbox link: https://fbhp--bpspdev.sandbox.my.site.com/shopper/s/quotepage?ChooseProductType1=Medical&state=TN&language=en_US
2. Start JAWS and invoke the FormField dialog box (Insert+F5). Note that the **Address** and **County** boxes are required on the page, but not required in FormField dialog box (no asterisk (*)).
3. Note that in Chrome Dev-Tools, both elements have the `required` attribute.

#### JAWS version and build number

2022.2207.75
 
#### Operating System and version

Windows 19042.2130

#### Browser and version:

Chrome 107.0.5304.87

![Screen Shot 2022-11-03 at 10 56 54 AM](https://user-images.githubusercontent.com/116229754/199803180-f77f11fb-86e1-4b51-b4bf-ad87806ee111.png)

**Comment by JAWS-test** [comment]
The asterisk does not come from the required attribute, but from the * in the label for element. For some fields in your form the visible label is overwritten by an aria-label in the label for. That's why the AccName is without an asterisk and thus it is not output by JAWS and NVDA. This is a bug in your application. Please remove the aria-label in your application or add the asterisk to the aria-label and close the ticket here.

**Comment by soehlerSF** [comment]
I will attempt the fix here and return, thank you.

**Comment by soehlerSF** [comment]
Thank you for pointing out the inconsistency in our application of aria-label; we've attempted both fixes you suggested and both worked. Closing this out.
