### ISSUE TITLE
role="application" is not in list of regions in JAWS 2018

### ISSUE THREAD

**Issue by gdkraus** [FreedomScientific/VFO-standards-support#69]
### Summary

An element with role="application" is not in the list of items that can be reached when navigating by region ("r" key). This is true even if the role="application" has an aria-label. This used to work in JAWS 18

### Expected result

The element with role="application" should have been in the list of items the user can navigate to using the "r" key

### Actual result

The role="application" element is skipped over

### Example

https://codepen.io/gdkraus-sas/full/bvyKQj/

### Additional Information

This appears to be a regression from behavior in JAWS 18.

#### JAWS version and build number

2018.1803.24
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 65

**Comment by stevefaulkner** [comment]
@gdkraus `role=application` is no longer defined as [a landmark in ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#landmark_roles), therefore is not included as a region in JAWS region navigation.
