### ISSUE TITLE
ARIA combobox does not close on escape key

### ISSUE THREAD

**Issue by curtbellew** [FreedomScientific/VFO-standards-support#695]
### Summary

1. Using the W3C's combobox demo at https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html .
2. Focus on the combobox labelled 'Favorite Fruit'
3. Using the down arrow, open the combobox drop down
4. Hit the 'Esc' key

### Expected result

With or without JAWS running, the drop down should close.

### Actual result

When JAWS is not running, the drop down will close.

When JAWS is running, hitting the escape key throws JAWS in to virtual cursor mode but does not close the drop down.  Hitting the 'Esc' key a second time does then close the drop down.

Here is the history from interaction using JAWS --
Choose a Fruit
To change the selection use the Arrow keys.
Favorite Fruit  List box  
Banana 
3 of 13
To move to an item press the Arrow keys.
virtual PC Cursor <== The first time I hit the 'Esc' key
Favorite Fruit  Combo box   <== The second time I hit the 'Esc' key
Choose a Fruit
To change the selection use the Arrow keys.

### Example

[> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...](https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html)

### Additional Information

I duplicated the issue using Chrome and Firefox
I was also able to duplicate this in NVDA.
The issue did not duplicate on MacOS using Voiceiver and Chrome

#### JAWS version and build number

Version: 2023.2210.29 ILM
 
#### Operating System and version

Windows 10 Pro. 21h2

#### Browser and version:
Chrome: Version 109.0.5414.75 (Official Build) (64-bit)
Firefox: 102.7.0esr (32-bit)

**Comment by JAWS-test** [comment]
There is no other way as long as JAWS uses the ESC key to exit forms mode. Since most JAWS users probably got used to ESC to exit forms mode and thus always have to press ESC 2x in such cases (not limited to the select-only combobox), I would rather be in favor of accepting the bug in rather than abolishing ESC as JAWS key to exit forms mode

**Comment by JAWS-test** [comment]
Related: https://github.com/FreedomScientific/VFO-standards-support/issues/528 and https://github.com/FreedomScientific/VFO-standards-support/issues/339

**Comment by stevefaulkner** [comment]
Closing this as it is a case of conflicting key strokes
