### ISSUE TITLE
JAWS announces "blank" for buttons in columns 2+ in a treegrid with virtual cursor off

### ISSUE THREAD

**Issue by kabsas** [FreedomScientific/VFO-standards-support#707]
### Summary

JAWS announces "blank" for buttons in columns 2+ in a treegrid with virtual cursor off.

Steps to reproduce:

1. Launch JAWS
2. Go to https://codepen.io/calascionec/pen/ZEopQxo (Note: this treegrid has no expand/collapse elements it is simply to demostrate the bug)
3. Turn off virtual cursor (Ctrl+Z)
4. Navigate the buttons in the treegrid via Tab key

### Expected result

All buttons in the treegrid are announced as the visible name (Action 1, Action 2, Action 3, Action 4)

### Actual result

The Action 1 buttons in column 1 are announced as expected. The buttons in columns 2-4 are announced as "blank"

#### JAWS version and build number
2023.2302.15

#### Operating System and version
Windows 10 Enterprise 19044.2604

#### Browser and version:
Chrome 111
Edge 111
Firefox 110

**Comment by stevefaulkner** [comment]
@kabsas I can reproduce, but am unclear about your usecase? Grids and treegrids need to handle keyboard interaction via JavaScript as per https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/#kbd_label
When [arrow key navigation is added to your example](https://cdpn.io/pen/debug/WNaPoON), the button labels are announced as expected.

**Comment by stevefaulkner** [comment]
> @stevefaulkner - it looks like this issue has been fixed in the June release 2023.2306.38

thanks @kabsas
