### ISSUE TITLE
JAWS in IE 11 does not honor aria-hidden="true" on role="tree"

### ISSUE THREAD

**Issue by gdkraus** [FreedomScientific/VFO-standards-support#71]
### Summary

JAWS 2018 in IE 11 does not honor aria-hidden="true" on elements with role="tree".

### Expected result

When aria-hidden="true" is on an element with role="tree", the user should not be able to navigate to it with the virtual cursor, and it should not be in the list of form elements.

### Actual result

The user can find the tree both with the virtual cursor and when listing all form elements.

### Example

https://codepen.io/gdkraus-sas/full/qYBLqa/

Note: this is not a fully implemented ARIA tree, but the problem manifests itself with the simplest of structures. This was originally discovered in an application where a modal dialog was opened, aria-hidden="true" was applied to all of the background elements, but the user could still navigate to the tree using the virtual cursor.

#### JAWS version and build number

JAWS (effects versions 17, 18, and 2018). I didn't check back any further.
 
#### Operating System and version

Windows 10

#### Browser and version:

IE 11

**Comment by TPGJRogers** [comment]
Issue is marked IE11. Closing.
