### ISSUE TITLE
Focus not trapped in modal-dialog when focus is initially set on a text input.

### ISSUE THREAD

**Issue by jjwright1701** [FreedomScientific/VFO-standards-support#710]
### Summary

1. Go to https://accessibility.hhs.texas.gov/acidtests/aria/dialog_modal.htm.
2. Turn on JAWS
3. Open the modal dialog

### Expected result

Virtual cursor should now be trapped in the modal dialog.

### Actual result

You can navigate outside the dialog with arrow keys.

#### JAWS version and build number

2022.2207 and others
 
#### Operating System and version

Windows 10 Enterprise 19044.2728

#### Browser and version:

Edge 112.0.1722.34 and others

**Comment by JAWS-test** [comment]
Checked it with Chrome and Edge, with JAWS 2022 and 2023: I do not have the bug. The arrow key navigation with the virtual cursor is limited to the modal dialog
