### ISSUE TITLE
Jaws pressing escape after down arrowing in tooltip causes incorrect focus

### ISSUE THREAD

**Issue by mespe-epic** [FreedomScientific/VFO-standards-support#715]
### Summary
1. Tab to an icon which opens up a tooltip with content that can be navigated with arrow keys
2. Down arrow once inside the tooltip to read content
3. Press Escape
4. JAWS focus (red box) will stay where the text used to be, but nothing will be there on the screen
5. Press tab, focus seems to jump to a random spot where user would not expect

### Expected result
The expected result is that after pressing escape, the focus is returned to the icon which revealed the tool tip

### Actual result
The actual result was that the JAWS focus remained on where the text in the tool tip used to be after pressing escape.

#### JAWS version and build number
JAWS 2023

 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome/Edge

**Comment by stevefaulkner** [comment]
@mespe-epic please provide a test case

**Comment by JAWS-test** [comment]
Even without example: The application is responsible for the correct focus handling, this has to be done via JS
