### ISSUE TITLE
Slider has slow performance when holding arrow keys

### ISSUE THREAD

**Issue by stmonson** [FreedomScientific/VFO-standards-support#717]
### Summary

1. Go to https://www.w3schools.com/howto/howto_js_rangeslider.asp (with JAWS running)
2. Set focus on any of the sliders there
3. Hold left or right arrow key

### Expected result
Similar behavior of moving right or left when Jaws isn't running

### Actual result
It does continue to move left or right, but very slowely and continues after you stop holding the key far longer

#### JAWS version and build number

2022.2211.7 ILM
 
#### Operating System and version

Windows 11

#### Browser and version:

Chrome 113.0.5672.93

**Comment by stevefaulkner** [comment]
@stmonson  get the same in JAWS 2023, but works fine when using the Home/End/PgUp/PgDn arrow keys to move quickly through the slider value.
