### ISSUE TITLE
Slider repeats final value when holding arrow keys

### ISSUE THREAD

**Issue by stmonson** [FreedomScientific/VFO-standards-support#718]
### Summary

1. Go to https://www.w3schools.com/howto/howto_js_rangeslider.asp with JAWS running
2. Hold the left/right arrow key with focus on one of the sliders

### Expected result

The final value to be read once

### Actual result

Jaws reads the final value repeatedly (as many times as it moved while holding the arrow key?)

#### JAWS version and build number

2022.2211.7 ILM
 
#### Operating System and version

Windows 11

#### Browser and version:

Chrome 113.0.5672.93

**Comment by stevefaulkner** [comment]
@stmonson could not reproduce issue in JAWS 2023
