### ISSUE TITLE
JAWS 18 not rendering the element mapped with aria-labelledby

### ISSUE THREAD

**Issue by Lnandana** [FreedomScientific/VFO-standards-support#72]
### Summary

> The label for a native HTML input element is provided using attribute aria-labelledby that is mapped to a span. JAWS is not rendering the content of the mapped element

### Expected result

> The label should be rendered correctly.

### Actual result
Label is not rendered, just placeholder text has been announced

> What actually did happen?

### 

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

**Comment by stevefaulkner** [comment]
Hi @Lnandana can you please provide an example page that exhibits the behaviour you are describing, thanks.

**Comment by ggordon-vfo** [comment]
Never received an example. Closing issue.
