### ISSUE TITLE
JAWS 18 and IE 11 with modal reading the close button as x 

### ISSUE THREAD

**Issue by amad4biz** [FreedomScientific/VFO-standards-support#74]
### Summary

Jaws 18 with IE 11 is reading close button as X before continuing to read the modal content. However, I tested it with NVDA 2017, everything is reading fine

### Expected result

> What did you expect to happen?

I expect JAWS no to read the close button as X. it should read close as it is doing with NVDA

> What actually did happen?

### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

please see my modal below

https://codepen.io/amad4biz/pen/gzwBKw

#### JAWS version and build number
JAWS 2018 with IE11

 
#### Operating System and version

Windows 7/10

#### Browser and version:

Internet explorer

**Comment by scottaohara** [comment]
Retesting today IE11 + JAWS 2019 will announce the close button as "times" when the dialog opens and JAWS begins reading the contents of the dialog from start to end.

[Removing the button from the dialog](https://scottaohara.github.io/testing/buttons/ie11-aria-label-test.html) the issue did not occur.

Using aViewer and inspecting the dialog, IE11 is grabbing all the text of the dialog and using it to create its accessible name.  

MSAA's accName value for the dialog is "simple title &times; Content text OK"

When navigating the dialog with the <kbd>tab</kbd> key or manually via the virtual cursor or hot keys, the close button is announced as expected.

If providing the modal dialog with an accessible name (e.g. `aria-label="f00"`) and then opening the dialog, JAWS will announce the accName and then begin *correctly* announcing the content of the dialog.
