### ISSUE TITLE
JAWS Crash moving between applications

### ISSUE THREAD

**Issue by kakinney** [FreedomScientific/VFO-standards-support#75]
### Summary

Trying to move back and forth between applications.  Moving between Chrome and Excel it keeps hanging and then crashing.

### Expected result
This was working fine, but just this week it started acting up.  - JAWS crashed just opening it and trying to get my version number.  so with JAWS open going between the Error log in computer management and Chrome 66 browser

### Actual result

JAWS crashes

### Example
Error Log file:
The program jfw.exe version 18.0.4534.400 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: 1620
 Start Time: 01d3de302fca8de9
 Termination Time: 46
 Application Path: C:\Program Files\Freedom Scientific\JAWS\18.0\jfw.exe
 Report Id: d1006379-4a23-11e8-82bc-e4a7a0af0531
 Faulting package full name: 
 Faulting package-relative application ID: 

Application Failure log file:
Fault bucket 2264205132238118773, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: jfw.exe
P2: 18.0.4534.400
P3: 5a285f07
P4: 443e
P5: 134217984
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
C:\Users\kakinney\AppData\Local\Temp\WER1FE5.tmp.appcompat.txt
C:\Users\kakinney\AppData\Local\Temp\WER3EF7.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\kakinney\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppHang_jfw.exe_eff5337438923ad3c6194a1c4451f40979de77e_60248b8c_22be4510

Analysis symbol: 
Rechecking for solution: 0
Report Id: d1006379-4a23-11e8-82bc-e4a7a0af0531
Report Status: 0
Hashed bucket: 2ee16da72f07ad602f6c12924dab5f75

#### JAWS version and build number

JAWS 18.0.4534
 
#### Operating System and version

Windows 8

#### Browser and version:
Chromium browser 51 and Chrome 66

**Comment by stevefaulkner** [comment]
Hi @kakinney apologies, but this is not the right place to file such bugs. This bug tracker is for issues with JAWS support for ARIA, CSS, HTML, or SVG Please contact [Freedom Scientific](https://www.freedomscientific.com/About/ContactUs) to report general issues with JAWS.
