### ISSUE TITLE
Combobox with form fields dialog

### ISSUE THREAD

**Issue by elenastoyanovaa** [FreedomScientific/VFO-standards-support#77]
### Summary

Having an element with role combobox and opening the form fields dialog (Ins+F5) shows combobox items as unlabelled, even though they are.
Example:
1. Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html
2. Ins+f5 to open the dialog. Combobox elements are unlabelled

### Expected result

If you test the same thing on a sample of an input element, the input is labelled as expected, therefore the elements with role combobox should appear labelled also, when a label is present.

#### JAWS version and build number
JAWS 18

#### Operating System and version
Windows 10

#### Browser and version:
Internet Explorer

**Comment by stevefaulkner** [comment]
@elenastoyanovaa there is a lot of information you have not provided, that is needed to respond to this bug, please supply.

Expected result

    What did you expect to happen?

Actual result

    What actually did happen?

Additional Information:
JAWS version and build number
Operating System and version
Browser and version:

**Comment by stevefaulkner** [comment]
Have tested with JAWS 2018 1804.32  and can reproduce, using [test case ](https://s.codepen.io/stevef/debug/odWpRZ). Note the autocomplete does not work in the test case.

**Comment by stevefaulkner** [comment]
Added reference to existing bug  #97770 - ARIA combobox is not read properly

**Comment by carmacleod** [comment]
Related: https://github.com/w3c/aria/issues/909, https://github.com/w3c/aria-practices/issues/886, https://github.com/w3c/aria/issues/893

**Comment by TPGJRogers** [comment]
Issue is marked IE11. Closing.
