### ISSUE TITLE
JAWS 2018 1805.33 speaks polite ARIA live region in Chrome even when tab is not active

### ISSUE THREAD

**Issue by mraccess77** [FreedomScientific/VFO-standards-support#84]
polite ARIA live content announced for page tab that is not active tab in Chrome.

Example:
1. Open Chrome
2. Go to https://labs.levelaccess.com/index.php/ARIA_Live
3 Activate auto update button
4 Switch tabs
5 Hear live region announced

### Expected result

The polite region should not be announced when the tab is not active.

### Actual result

> What actually did happen?

### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

**Comment by JAWS-test** [comment]
The problem no longer exists and the ticket can be closed. See: https://github.com/FreedomScientific/VFO-standards-support/issues/293

**Comment by lamador** [comment]
Not reproducible with latest version of JAWS (ver 2020.2004.66) and Chrome (ver 81.0.4044.138).
