### ISSUE TITLE
JAWS 2018.1805.33 and prior temporary delay when using control+backspace in Github textarea with Chrome

### ISSUE THREAD

**Issue by mraccess77** [FreedomScientific/VFO-standards-support#85]
When editing an issues such as this control+backspace delays temporarily in text area.  This does not happen in a standard input.

1. From this site choose "new issue" in Chrome
2. Issue text area field appears
3  Type in several words of text.    Press control+backspace to delete the prior word. 
4. Notice the delay

### Expected result
No delay should be present when using control+backspace.

### Actual result
A marked delay occurs before the word is deleted

#### JAWS version and build number
2018.1805.33
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome

**Comment by stevefaulkner** [comment]
Can reproduce

**Comment by ggordon-vfo** [comment]
No longer replicates with Chrome 72 and JAWS 2019 June update. Closing issue.
