### ISSUE TITLE
JAWS and Chrome RadioGroups using aria-activedescendant JAWS Does Not Switch to the PC Cursor when Navigating into a Radio Button Group using the Tab Key if VPC Active

### ISSUE THREAD

**Issue by jhartleytpgi** [FreedomScientific/VFO-standards-support#853]
### Summary
if Tab or Shift+Tab is used to navigate into a radio button group when virtual cursor is active, JAWS does Not Switch from virtual cursor to PC cursor. This is true even with the AutoFormsMode setting set to Auto.

### Expected result

JAWS should switch to the PC cursor  (turn on forms mode) once the radio button group is
navigated into using the Tab key.
### Actual result

The Virtual PC cursor remains the active cursor. Users must press Enter to manually switch on forms mode.
### Example
https://aria-at.netlify.app/tests/radiogroup-aria-activedescendant/reference/2022-4-7_113015/radio-activedescendant.setfocusonfirstradiobutton

#### JAWS version and build number
2024.2406.121

#### Operating System and version
Windows 10 / 11

#### Browser and version:
Google Chrome
126.0.6478.183 (Official Build) (64-bit)

**Comment by JAWS-test** [comment]
it is not a bug, see: https://github.com/FreedomScientific/standards-support/issues/448, https://tink.uk/understanding-screen-reader-interaction-modes/

**Comment by BrettLewisVispero** [comment]
We do consider this a bug if you are tabbing into a radio group. If forms mode is not set to auto then we want to keep the virtual cursor active but tabbing into the radio group should enable forms mode.
