### ISSUE TITLE
Win32 Task Dialog content not narrated

### ISSUE THREAD

**Issue by juliekoubova** [FreedomScientific/VFO-standards-support#865]
### Summary

When a standard [Win32 Task Dialog](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-taskdialogindirect) is opened, only the selected button is narrated. The dialog heading and content is ignored.

The heading is narrated when you Alt-Tab into a different window and then return to the dialog, but the content is not read even then.

### Expected result

All the content to be read before narrating the button.

### Actual result

Only the selected button is narrated.

### Example

```cpp
#pragma comment(lib, "comctl32.lib")
#pragma comment( \
    linker,      \
    "/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <CommCtrl.h>

int WINAPI wWinMain(_In_ HINSTANCE, _In_opt_ HINSTANCE, _In_ LPWSTR, _In_ int)
{
	TASKDIALOGCONFIG config{ sizeof(config) };
	config.pszMainInstruction = L"Hello, World";
	config.pszContent = L"What's up?";
	config.pszVerificationText = L"Howdy";
	BOOL check;
	TaskDialogIndirect(&config, NULL, NULL, &check);
	return 0;
}
```

#### JAWS version and build number

JAWS 2024.2406.121

#### Operating System and version

Windows 11 22621.1

**Comment by stevefaulkner** [comment]
Hi @juliekoubova this issue tracker is for HTML/ARIA web only, so closing here. @BrettLewisVispero @ggordon-vispero can you point @juliekoubova to the best place to file this issue, thanks!
