### ISSUE TITLE
Clicking on a button that triggers update to document will cause focus to shift in FF 60

### ISSUE THREAD

**Issue by jessegreenberg** [FreedomScientific/VFO-standards-support#88]
### Summary
In FF 60, clicking more than once on a button that triggers some change in the document will cause focus to shift. I have reproduced in a few web pages, but it is easiest to see here:

1. Go to http://jsfiddle.net/rL8zt0q1/2/
2. Navigate to "Update Readout" button.
3. Click the button (focus will stay on the button, button will be clicked).
4. Click the button again (focus will move to different button and that button will be clicked instead).

The shift in focus doesn't occur if any of the other buttons are clicked. In this example, clicking the button changes `innerHTML` on a paragraph element, but other things might cause this bug too.

### Expected result
I expect focus not to change after clicking a button more than once.

### Actual result
Focus moves to a previous focusable element after clicking on the button, if clicking the button updates the document.

### Example
http://jsfiddle.net/rL8zt0q1/2/

#### JAWS version and build number
2018.1805.33

#### Operating System and version
Windows 10

#### Browser and version:
Firefox 60.0.1

**Comment by jessegreenberg** [comment]
It also happens with basic check boxes: http://jsfiddle.net/rL8zt0q1/8/

**Comment by stevefaulkner** [comment]
codepen [test case](https://codepen.io/stevef/pen/JZbdRY) for buttons. @jessegreenberg recreating in codepen for my own purposes.

**Comment by jessegreenberg** [comment]
Thanks @stevefaulkner. In another context, this has caused JAWS to accidentally click on a link that took me to a new web page rather than clicking on the button that had focus.

**Comment by stevefaulkner** [comment]
@jessegreenberg I can reproduce and seems like a JAWS bug, will file an issue and post details here. Thanks for reporting!

**Comment by jessegreenberg** [comment]
Great, thanks @stevefaulkner!

**Comment by stevefaulkner** [comment]
filed internally  as Bug 101898 - Clicking on a button that triggers update to document will cause focus to shift in FF 60

**Comment by ggordon-vfo** [comment]
This works in Firefox 67 and JAWS 2019 June update. Closing issue.
