### ISSUE TITLE
Listbox-Options Read Incorrectly After Tabbing Off to Button (Firefox 61 only)

### ISSUE THREAD

**Issue by tmatsui213** [FreedomScientific/VFO-standards-support#99]
### Summary

In Firefox 61, if we have a group of div marked with role="option", followed by a button, tab through all elements to get tot the button, and then shift+tab back to the option, the option gets read as if focus is still on the button.

This works fine on Chrome and Edge

Here's a jsfiddle where this is happening:
[https://jsfiddle.net/x76a0k1z/7/](url)

### Expected result

Shift+Tabbing back to Option3, I would expect that to be read as something like "Option 3, 3 of 3".

### Actual result

Focus moves to Option3, but it gets read as "Next Button"

### Example

From above jsfiddle:
```
<div class="container" role="listbox">
  <div class="option" role="option" aria-selected="false" tabindex="0">
  Option 1
  </div>
  <div class="option" role="option" aria-selected="false" tabindex="0">
  Option 2
  </div>
  <div class="option" role="option" aria-selected="false" tabindex="0">
  Option 3
  </div>
</div>
<div class="buttons">
  <input type="button" value="Next" />
  <input type="button" value="Cancel" />
</div>
```

#### JAWS version and build number
2018.1803.33
 
#### Operating System and version
Windows 10 Enterprise

#### Browser and version:
Firefox 61.02

**Comment by ggordon-vfo** [comment]
Works with Firefox 67 and JAWS 2019 June update. Earlier versions of JAWS 2019 will likely work as well. Closing issue.
